Repository buildtesters/buildtest, pull requests merged in 2020-04, with the labels that each got.

#252 adding basic steps for a local (base) executor
  buildtest/buildsystem/base.py
  buildtest/executors/base.py
  buildtest/menu/__init__.py
  buildtest/menu/build.py
  tests/executors/test_base.py
Labels: size/L, ✅ Approved

#260 remove backup configuration settings.yml.bak.
  buildtest/config.py
  buildtest/defaults.py
  buildtest/menu/__init__.py
  buildtest/menu/config.py
  tests/menu/test_config.py
Labels: size/M, ✅ Approved

#255 Reorg valid config schema for regtest
  buildtest/buildsystem/schemas/utils.py
  tests/examples/config_schemas/valid/combined-example.yml
  tests/examples/config_schemas/valid/local-example.json
  tests/examples/config_schemas/valid/local-example.yml
  tests/examples/config_schemas/valid/slurm-example.yml
  tests/executors/test_base.py
  tests/menu/test_config.py
Labels: ✅ Approved

#261 Add support for specifying buildtest settings from cli
  buildtest/config.py
  buildtest/defaults.py
  buildtest/executors/base.py
  buildtest/main.py
  buildtest/menu/__init__.py
  buildtest/menu/build.py
  buildtest/menu/config.py
  tests/menu/test_config.py
  tests/test_config.py
  tests/test_defaults.py
Labels: size/M, ✅ Approved

#264 Change output behavior of buildtest build, add system log, add .err file per test
  buildtest/buildsystem/base.py
  buildtest/buildsystem/schemas/utils.py
  buildtest/config.py
  buildtest/executors/base.py
  buildtest/main.py
  buildtest/menu/build.py
  buildtest/system.py
  buildtest/utils/file.py
  tests/buildsystem/schemas/__init__.py
  tests/buildsystem/schemas/test_utils.py
  tests/menu/test_build.py
Labels: size/L, 🔍 Ready for Review

#268 exclude config option
  buildtest/menu/__init__.py
  buildtest/menu/build.py
  buildtest/utils/file.py
  examples/script/bzip2.yml
  examples/script/zlib.yml
Labels: size/L, 🔍 Ready for Review

#269 Redefinition of buildtest terms
  docs/index.rst
  docs/terminology.rst
Labels: size/M, ✅ Approved

#271 fixing saving of output for BuildTestCommand
  buildtest/utils/command.py
Labels: size/S, ✅ Approved

#270 refactor codebase to use name buildspec
  buildtest/buildsystem/base.py
  buildtest/buildsystem/schemas/global.schema.json
  buildtest/config.py
  buildtest/defaults.py
  buildtest/executors/base.py
  buildtest/log.py
  buildtest/menu/__init__.py
  buildtest/menu/build.py
  buildtest/menu/config.py
  buildtest/menu/get.py
  buildtest/settings/settings.schema.json
  buildtest/settings/settings.yml
  buildtest/utils/file.py
  tests/buildsystem/test_base.py
  tests/executors/test_base.py
  tests/menu/test_build.py
  tests/menu/test_config.py
  tests/menu/test_get.py
  tests/test_config.py
  tests/utils/test_file.py
Labels: size/L, 🔍 Ready for Review

#276 add support for passing --buildspec multiple times
  buildtest/menu/__init__.py
  buildtest/menu/build.py
  tests/utils/test_file.py
Labels: size/S, ✅ Approved

#277 Making some general fixs
  buildtest/buildsystem/base.py
  buildtest/config.py
  buildtest/menu/build.py
  buildtest/menu/get.py
  buildtest/utils/file.py
  tests/buildsystem/test_base.py
  tests/test_config.py
  tests/utils/test_file.py
Labels: size/L, ✅ Approved

#278 Update settings schema field $id and title
  buildtest/settings/settings.schema.json
Labels: size/XS, ✅ Approved

#279 sync script schema from schema repo
  buildtest/buildsystem/schemas/script/script-v0.0.1.schema.json
Labels: size/S, ✅ Approved

#285 update org and repo name
  .github/workflows/urlchecker.yml
  CHANGELOG.rst
  CONTRIBUTING.rst
  README.rst
  buildtest/buildsystem/base.py
  buildtest/buildsystem/schemas/global.schema.json
  buildtest/buildsystem/schemas/script/script-v0.0.1.schema.json
  buildtest/defaults.py
  buildtest/menu/build.py
  buildtest/settings/settings.schema.json
  docs/api/buildtest.menu.rst
  docs/conf.py
  docs/contributing.rst
  docs/contributing/github_integration.rst
  docs/contributing/maintainer_guide.rst
  docs/contributing/regression_testing.rst
  docs/contributing/setup.rst
  docs/getting_started.rst
  docs/index.rst
  docs/installing_buildtest.rst
  docs/references.rst
  docs/what_is_buildtest.rst
  setup.py
  tests/menu/test_get.py
Labels: size/L, ✅ Approved

#288 Update getting started
  LICENSE
  buildtest/buildsystem/base.py
  buildtest/buildsystem/schemas/utils.py
  buildtest/docgen/main.py
  buildtest/executors/base.py
  docs/conf.py
  docs/docgen/buildtest_show_schema.txt
  docs/getting_started.rst
  docs/index.rst
  docs/installing_buildtest.rst
  docs/introspection.rst
  docs/spider.rst
  docs/what_is_buildtest.rst
  tests/buildsystem/test_base.py
  tests/executors/test_base.py
Labels: size/XL, 🔍 Ready for Review

#286 Status check
  buildtest/buildsystem/base.py
  buildtest/menu/build.py
  buildtest/utils/command.py
  buildtest/utils/file.py
  tests/utils/test_file.py
Labels: size/L, 🔍 Ready for Review

#289 Fix/command out err
  buildtest/utils/command.py
Labels: size/M, 🔍 Ready for Review
