Repository buildtesters/buildtest, pull requests merged in 2020-02, with the labels that each got.

#155 change test configuration name back to file-separator instead of "." …
  buildtest/docgen/main.py
  buildtest/tools/build.py
  buildtest/tools/config.py
  buildtest/tools/testconfigs.py
  buildtest/tools/writer.py
  docs/build_subcommand/build.rst
  docs/build_subcommand/module_collections.rst
  docs/docgen/build-report.txt
  docs/docgen/build-run-example.txt
  docs/docgen/build-test-example.txt
  docs/docgen/buildtest_module_--software.txt
  docs/docgen/buildtest_module_list.txt
  docs/docgen/buildtest_show_--config.txt
  docs/docgen/buildtest_system_view.txt
  docs/docgen/buildtest_testconfigs_-h.txt
  docs/docgen/buildtest_testconfigs_list.txt
  docs/docgen/buildtest_testconfigs_maintainer_-h.txt
  docs/docgen/buildtest_testconfigs_view_tutorial_compilers_args.c.yml
  docs/docgen/module-diff-trees.txt
  docs/docgen/module_collection_add.txt
  docs/docgen/module_collection_remove.txt
  docs/docgen/moduleload-test.txt
  docs/docgen/tutorial.compilers.args.c.yml.txt
  docs/docgen/tutorial.compilers.args.c.yml_dry.txt
  docs/docgen/tutorial.compilers.args.c.yml_v.txt
  docs/docgen/tutorial.compilers.hello.f.yml.txt
  docs/docgen/tutorial.compilers.hello_lsf.yml.txt
  docs/docgen/tutorial.compilers.hello_slurm.yml.txt
  docs/docgen/tutorial.openacc.vecAdd.c.yml.txt
  docs/docgen/tutorial.openacc.vecAdd.c_pgi.yml.txt
  docs/docgen/tutorial.openmp.clang_hello.c.yml.txt
  docs/managing_testconfigs.rst
  docs/scripts/build-lmod-collection-example.txt
  docs/scripts/build-module-collection-example.txt
  docs/scripts/build-module-permutation-example.txt
Labels: size/XL, 🔍 Ready for Review

#156 removing module permutation feature for now. Remove example from
  buildtest/tools/build.py
  buildtest/tools/menu.py
  docs/build_subcommand/module_collections.rst
  docs/docgen/build-report.txt
  docs/docgen/build-run-example.txt
  docs/docgen/build-test-example.txt
  docs/docgen/buildtest_build_-h.txt
  docs/docgen/module-diff-trees.txt
  docs/docgen/tutorial.compilers.args.c.yml.txt
  docs/docgen/tutorial.compilers.args.c.yml_dry.txt
  docs/docgen/tutorial.compilers.args.c.yml_v.txt
  docs/docgen/tutorial.compilers.hello.f.yml.txt
  docs/docgen/tutorial.compilers.hello_lsf.yml.txt
  docs/docgen/tutorial.compilers.hello_slurm.yml.txt
  docs/docgen/tutorial.openacc.vecAdd.c.yml.txt
  docs/docgen/tutorial.openacc.vecAdd.c_pgi.yml.txt
  docs/docgen/tutorial.openmp.clang_hello.c.yml.txt
  docs/managing_testconfigs.rst
  docs/scripts/build-module-permutation-example.txt
Labels: size/L, 🔍 Ready for Review

#160 Remove pip packaging
  MANIFEST.in
  bin/buildtest
  setup.py
Labels: 🔍 Ready for Review

#163 removing buildtest build [run|log|test] option from build menu.
  buildtest/tools/build.py
  buildtest/tools/buildsystem/status.py
  buildtest/tools/menu.py
Labels: size/L, 🔍 Ready for Review

#164 remove the coverage notify section since it is not working. Change co…
  .codecov.yml
Labels: size/S, 🔍 Ready for Review

#165 adding separate page on Lmod spider in documentation
  docs/index.rst
  docs/module_operation.rst
  docs/spider.rst
Labels: size/L, 🔍 Ready for Review

#166 changing most of open() file handles to use with open().
  buildtest/tools/build.py
  buildtest/tools/buildsystem/status.py
  buildtest/tools/menu.py
  buildtest/tools/modulesystem/collection.py
  buildtest/tools/modulesystem/tree.py
  tests/test_build.py
Labels: size/L, 🔍 Ready for Review

#167 remove -v (verbose) option from buildtest build.
  buildtest/docgen/main.py
  buildtest/tools/build.py
  buildtest/tools/buildsystem/singlesource.py
  buildtest/tools/menu.py
  buildtest/tools/writer.py
  docs/build_subcommand/build_status.rst
  docs/docgen/build-run-example.txt
  docs/docgen/build-test-example.txt
  docs/docgen/tutorial.compilers.hello_lsf.yml.txt
  docs/docgen/tutorial.compilers.hello_slurm.yml.txt
Labels: size/L, 🔍 Ready for Review

#172 Add black checks
  .github/workflows/black.yml
  buildtest/docgen/main.py
  buildtest/main.py
  buildtest/tools/build.py
  buildtest/tools/buildsystem/singlesource.py
  buildtest/tools/buildsystem/status.py
  buildtest/tools/config.py
  buildtest/tools/configuration/config.py
  buildtest/tools/menu.py
  buildtest/tools/modules.py
  buildtest/tools/modulesystem/collection.py
  buildtest/tools/modulesystem/tree.py
  buildtest/tools/show.py
  buildtest/tools/system.py
  buildtest/tools/testconfigs.py
  buildtest/tools/writer.py
  tests/test_build.py
  tests/test_config_file.py
  tests/test_file.py
  tests/test_inspect.py
  tests/test_module_collection.py
  tests/test_module_tree.py
  tests/test_modules.py
  tests/test_testconfigs.py
Labels: size/M, 🔍 Ready for Review

#173 Testing customized greeing to not run on forked pull requests
  .github/workflows/greetings.yml
Labels: size/S, 🔍 Ready for Review

#175 removing the sponsor page from GitHub for now. CommunityBridge won't
  .github/FUNDING.yml
Labels: size/XS, 🔍 Ready for Review

#176 Module api first attempt
  buildtest/modules/__init__.py
  buildtest/modules/util.py
  examples/collection.py
  examples/moduletest.py
Labels: 🔍 Ready for Review

#177 Start to add packaging, and toolkit installs
  .gitignore
  .travis.yml
  CHANGELOG.rst
  MANIFEST.in
  bin/buildtest
  buildtest/__init__.py
  buildtest/docgen/main.py
  buildtest/main.py
  buildtest/settings.yml
  buildtest/tools/build.py
  buildtest/tools/buildsystem/singlesource.py
  buildtest/tools/config.py
  buildtest/tools/defaults.py
  buildtest/tools/file.py
  buildtest/tools/get.py
  buildtest/tools/log.py
  buildtest/tools/menu.py
  buildtest/tools/modules.py
  buildtest/tools/modulesystem/collection.py
  buildtest/tools/system.py
  buildtest/tools/testconfigs.py
  buildtest/tools/writer.py
  docs/build_subcommand/build_examples.rst
  docs/configuring_buildtest.rst
  docs/installing_buildtest.rst
  setup.py
  sourceme.csh
  sourceme.sh
  tests/test_build.py
  tests/test_file.py
  toolkit/suite/tutorial/compilers/args.c.yml
  toolkit/suite/tutorial/compilers/hello.f.yml
  toolkit/suite/tutorial/compilers/module_key_example.yml
  toolkit/suite/tutorial/compilers/src/args.c
  toolkit/suite/tutorial/compilers/src/hello.c
  toolkit/suite/tutorial/compilers/src/hello.cpp
  toolkit/suite/tutorial/compilers/src/hello.f90
  toolkit/suite/tutorial/cuda/saxpy.c.yml
  toolkit/suite/tutorial/cuda/src/saxpy.c
  toolkit/suite/tutorial/mpi/hello.c.yml
  toolkit/suite/tutorial/mpi/src/hello.c
  toolkit/suite/tutorial/openacc/src/vecAdd.c
  toolkit/suite/tutorial/openacc/vecAdd.c.yml
  toolkit/suite/tutorial/openacc/vecAdd.c_pgi.yml
  toolkit/suite/tutorial/openmp/clang_hello.c.yml
  toolkit/suite/tutorial/openmp/lmod_collection_example.yml
  toolkit/suite/tutorial/openmp/omp_hello.c.yml
  toolkit/suite/tutorial/openmp/src/omp_hello.c
Labels: size/XXL, ✅ Approved

#179 Add pre commit hook for black
  .github/hooks/pre-commit
  docs/contributing.rst
Labels: size/M, ✅ Approved

#180 replacing toolkit/suite with site
  CHANGELOG.rst
  buildtest/tools/config.py
  buildtest/tools/defaults.py
  buildtest_regtest.py
  docs/build_subcommand/build.rst
  docs/build_subcommand/build_examples.rst
  docs/conf.py
  docs/docgen/tutorial.compilers.args.c.yml.txt
  docs/docgen/tutorial.compilers.args.c.yml_dry.txt
  docs/docgen/tutorial.compilers.args.c.yml_v.txt
  docs/docgen/tutorial.compilers.hello.f.yml.txt
  docs/docgen/tutorial.openacc.vecAdd.c.yml.txt
  docs/docgen/tutorial.openacc.vecAdd.c_pgi.yml.txt
  docs/docgen/tutorial.openmp.clang_hello.c.yml.txt
  docs/managing_testconfigs.rst
  docs/scripts/build-module-collection-example.txt
  docs/scripts/build-mpi-example.txt
  docs/scripts/buildtest-module-collection-update.txt
  setup.py
  site/benchmark/stream/src/mysecond.c
  site/benchmark/stream/src/stream.c
  site/benchmark/stream/stream.c.yml
Labels: ✅ Approved

#184 fixing hooks typo in docs and adding examples folder to commit
  .github/hooks/pre-commit
  .github/workflows/black.yml
  docs/contributing.rst
Labels: size/XS, ✅ Approved

#183 cleaning up code-base with any unused methods.
  buildtest/tools/config.py
  buildtest/tools/lsf.py
  buildtest/tools/menu.py
  buildtest/tools/slurm.py
  buildtest/tools/system.py
Labels: size/L, ✅ Approved

#181 second addition of module API.
  buildtest/module.py
  buildtest/modules/__init__.py
  buildtest/modules/util.py
  buildtest/spider.py
  examples/collection.py
  examples/moduletest.py
  examples/saving_collection.py
  examples/spider_example.py
Labels: size/L, 🔍 Ready for Review
