Repository buildtesters/buildtest, pull requests merged in 2020-06, with the labels that each got.

#307 adding pyflakes to buildtest to check for ununsed imports
  .github/workflows/black.yml
  buildtest/buildsystem/base.py
  buildtest/config.py
  buildtest/docgen/main.py
Labels: size/S, ✅ Approved

#309 update settings schema, and behavior of BuilderBase and BuildExecutor
  buildtest/buildsystem/base.py
  buildtest/buildsystem/schemas/compiler/compiler-v1.0.schema.json
  buildtest/buildsystem/schemas/script/script-v1.0.schema.json
  buildtest/buildsystem/schemas/utils.py
  buildtest/executors/base.py
  buildtest/main.py
  buildtest/menu/__init__.py
  buildtest/menu/build.py
  buildtest/menu/config.py
  buildtest/menu/get.py
  buildtest/settings/settings.schema.json
  buildtest/settings/settings.yml
  tests/buildsystem/test_base.py
  tests/examples/buildspecs/environment.yml
  tests/examples/buildspecs/python-shell.yml
  tests/examples/buildspecs/shell_examples.yml
  tests/examples/buildspecs/slurm.yml
  tests/examples/config_schemas/valid/combined-example.yml
  tests/examples/config_schemas/valid/local-example.json
  tests/examples/config_schemas/valid/local-example.yml
  tests/examples/config_schemas/valid/slurm-example.yml
  tests/executors/test_base.py
  tests/test_config.py
Labels: size/XL, 🔍 Ready for Review

#310 Update README.rst
  README.rst
Labels: size/XS, 🔍 Ready for Review

#311 update documentation for configuring buildtest and update schema section
  buildtest/main.py
  buildtest/menu/__init__.py
  buildtest/menu/build.py
  docs/configuring_buildtest.rst
  docs/schemas.rst
  docs/schemas/compiler.rst
  docs/schemas/global.rst
  docs/schemas/script.rst
Labels: size/M, 🔍 Ready for Review

#312 rename 'buildtest get' --> 'buildtest repo'
  buildtest/defaults.py
  buildtest/menu/__init__.py
  buildtest/menu/repo.py
  tests/buildsystem/test_base.py
  tests/executors/test_base.py
  tests/menu/test_build.py
  tests/menu/test_config.py
  tests/menu/test_get.py
  tests/menu/test_repo.py
  tests/test_config.py
  tests/utils/test_file.py
  tests/utils/test_shell.py
Labels: size/L, 🔍 Ready for Review

#313 Buildspec commands - view, edit, find
  buildtest/buildsystem/base.py
  buildtest/defaults.py
  buildtest/menu/__init__.py
  buildtest/menu/build.py
  buildtest/menu/buildspec.py
  tests/buildsystem/test_base.py
Labels: size/L, 🔍 Ready for Review

#314 move run implementation from BuilderBase to LocalExecutor
  buildtest/buildsystem/base.py
  buildtest/executors/base.py
  tests/buildsystem/test_base.py
  tests/executors/test_base.py
Labels: size/L, 🔍 Ready for Review

#315 remove Lmod installation from travis
  .travis.yml
  buildtest/buildsystem/base.py
  buildtest/executors/base.py
  buildtest/menu/__init__.py
  buildtest/menu/repo.py
  tests/menu/test_buildspec.py
  tests/menu/test_repo.py
Labels: size/L

#316 removing --dry option from buildtest build and clean up output of buildtest build
  .travis.yml
  buildtest/buildsystem/base.py
  buildtest/executors/base.py
  buildtest/menu/__init__.py
  buildtest/menu/build.py
  tests/menu/test_buildspec.py
  tests/menu/test_repo.py
Labels: size/L, 🔍 Ready for Review

#317 updating docs getting start guide with new output examples
  buildtest/docgen/main.py
  docs/api/buildtest.menu.buildspec.rst
  docs/api/buildtest.menu.repo.rst
  docs/api/buildtest.menu.rst
  docs/buildspec.error
  docs/buildtest.log
  docs/contributing.rst
  docs/contributing/build_documentation.rst
  docs/contributing/regression_testing.rst
  docs/docgen/buildtest_--help.txt
  docs/docgen/buildtest_build_--help.txt
  docs/docgen/buildtest_buildspec_--help.txt
  docs/docgen/buildtest_get_--help.txt
  docs/docgen/buildtest_repo_--help.txt
  docs/docgen/buildtest_show_schema_--help.txt
  docs/docgen/config-reset.txt
  docs/docgen/config-view.txt
  docs/docgen/gettingstarted-example1.txt
  docs/docgen/script-schema.txt
  docs/getting_started.rst
  docs/introspection.rst
Labels: size/XXL, 🔍 Ready for Review

#318 add getter methods for extracting repo entry and repo destination path
  buildtest/menu/build.py
  buildtest/menu/repo.py
  buildtest/settings/settings.schema.json
  buildtest/settings/settings.yml
  buildtest/settings/slurm-example.yml
  buildtest/settings/ssh-executor-example.yml
  tests/menu/test_repo.py
Labels: size/L, 🔍 Ready for Review

#319 Sync schemas
  buildtest/buildsystem/schemas/compiler/compiler-v1.0.schema.json
  buildtest/buildsystem/schemas/global.schema.json
  buildtest/buildsystem/schemas/script/script-v1.0.schema.json
  buildtest/settings/settings.schema.json
Labels: size/L, 🔍 Ready for Review

#321 add Timer class to time execution of test, log test result in json file and modify output of buildtest build
  buildtest/buildsystem/base.py
  buildtest/defaults.py
  buildtest/executors/base.py
  buildtest/menu/build.py
  buildtest/utils/timer.py
  tests/buildsystem/test_base.py
  tests/executors/test_base.py
  tests/run_tests.sh
Labels: size/L, 🔍 Ready for Review

#322 adding buildtest report command line option.
  buildtest/menu/__init__.py
  buildtest/menu/report.py
Labels: size/M, 🔍 Ready for Review

#323 change date format to YYYY-mm-dd for starttime/endtime and buildid to YYYY-mm-dd-HH-MM
  buildtest/buildsystem/base.py
  buildtest/executors/base.py
Labels: size/XS

#324 autogenerate getting started doc examples and fix few bugs
  buildtest/docgen/main.py
  buildtest/menu/build.py
  docs/api/buildtest.menu.report.rst
  docs/api/buildtest.menu.rst
  docs/api/buildtest.utils.rst
  docs/api/buildtest.utils.timer.rst
  docs/buildtest.log
  docs/docgen/buildtest_--help.txt
  docs/docgen/config-view.txt
  docs/docgen/getting_started/buildspec-abspath.txt
  docs/docgen/getting_started/buildspec-directory-and-file.txt
  docs/docgen/getting_started/buildspec-directory.txt
  docs/docgen/getting_started/buildspec-find.txt
  docs/docgen/getting_started/buildspec-relpath.txt
  docs/docgen/getting_started/buildspec-view.txt
  docs/docgen/getting_started/invalid-buildspec.txt
  docs/docgen/getting_started/invalid-executor.txt
  docs/docgen/getting_started/multi-buildspecs.txt
  docs/docgen/script-schema.txt
  docs/getting_started.rst
Labels: size/XL, 🔍 Ready for Review

#325 change "buildtest show schema" to "buildtest schema"
  buildtest/buildsystem/schemas/compiler/examples/1.0/invalid/examples.yml
  buildtest/buildsystem/schemas/compiler/examples/1.0/valid/examples.yml
  buildtest/buildsystem/schemas/global/examples/invalid/invalid_pattern.yml
  buildtest/buildsystem/schemas/global/examples/invalid/maintainers_type_mismatch.yml
  buildtest/buildsystem/schemas/global/examples/invalid/missing-version.yml
  buildtest/buildsystem/schemas/global/examples/valid/examples.yml
  buildtest/buildsystem/schemas/script/examples/1.0/invalid/examples.yml
  buildtest/buildsystem/schemas/script/examples/1.0/valid/examples.yml
  buildtest/buildsystem/schemas/settings/examples/valid/local-executor.yml
  buildtest/buildsystem/schemas/settings/examples/valid/slurm-example.yml
  buildtest/buildsystem/schemas/settings/examples/valid/ssh-executor-example.yml
  buildtest/buildsystem/schemas/utils.py
  buildtest/config.py
  buildtest/defaults.py
  buildtest/docgen/main.py
  buildtest/menu/__init__.py
  buildtest/menu/show.py
  docs/configuring_buildtest.rst
  docs/docgen/buildtest_--help.txt
  docs/docgen/buildtest_schema_--help.txt
  docs/docgen/buildtest_show_--help.txt
  docs/docgen/buildtest_show_schema_--help.txt
  docs/docgen/schemas/avail-schemas.txt
  docs/docgen/schemas/compiler-examples.txt
  docs/docgen/schemas/compiler-json.txt
  docs/docgen/schemas/global-examples.txt
  docs/docgen/schemas/global-json.txt
  docs/docgen/schemas/script-examples.txt
  docs/docgen/schemas/script-json.txt
  docs/docgen/schemas/settings-examples.txt
  docs/docgen/schemas/settings-json.txt
  docs/introspection.rst
  docs/schemas/compiler.rst
  docs/schemas/global.rst
  docs/schemas/script.rst
  tests/buildsystem/test_base.py
  tests/menu/test_show.py
Labels: 🔍 Ready for Review

#326 rename show.py to schema.py and remove execute perm from few source files.
  buildtest/exceptions.py
  buildtest/menu/__init__.py
  buildtest/menu/schema.py
  tests/buildsystem/test_base.py
  tests/menu/test_build.py
  tests/menu/test_repo.py
  tests/menu/test_schema.py
  tests/test_log.py
Labels: 🔍 Ready for Review

#327 Add option buildtest repo update to update repository configuration
  buildtest/menu/__init__.py
  buildtest/menu/repo.py
  tests/menu/test_repo.py
Labels: size/L, 🔍 Ready for Review

#329 Slurm executor
  buildtest/buildsystem/base.py
  buildtest/buildsystem/schemas/compiler/compiler-v1.0.schema.json
  buildtest/buildsystem/schemas/global.schema.json
  buildtest/buildsystem/schemas/script/script-v1.0.schema.json
  buildtest/executors/base.py
  buildtest/menu/build.py
Labels: size/L, 🔍 Ready for Review

#330 move implementation of updating test report to method update_report
  buildtest/buildsystem/base.py
  buildtest/executors/base.py
  buildtest/menu/build.py
  buildtest/menu/report.py
Labels: size/L, 🔍 Ready for Review

#331 Add option --clear in buildtest buildspec find which clears buildspec…
  buildtest/menu/__init__.py
  buildtest/menu/buildspec.py
  buildtest/menu/repo.py
  buildtest/utils/file.py
  tests/menu/test_buildspec.py
  tests/utils/test_file.py
Labels: size/M, 🔍 Ready for Review

#332 upgrading codecov version
  docs/requirements.txt
Labels: size/S, 🔍 Ready for Review

#333 adding vars key in compiler and script schema.
  buildtest/buildsystem/base.py
  buildtest/buildsystem/schemas/compiler/compiler-v1.0.schema.json
  buildtest/buildsystem/schemas/script/script-v1.0.schema.json
  tests/utils/test_file.py
Labels: size/M, 🔍 Ready for Review

#334 Poll interval
  buildtest/buildsystem/schemas/settings/examples/valid/slurm-example.yml
  buildtest/executors/base.py
  buildtest/settings/settings.schema.json
  buildtest/utils/command.py
Labels: size/M, 🔍 Ready for Review

#335 buildspec keyword in global schema
  buildtest/buildsystem/base.py
  buildtest/buildsystem/schemas/compiler/compiler-v1.0.schema.json
  buildtest/buildsystem/schemas/compiler/examples/1.0/invalid/examples.yml
  buildtest/buildsystem/schemas/compiler/examples/1.0/valid/examples.yml
  buildtest/buildsystem/schemas/global.schema.json
  buildtest/buildsystem/schemas/global/examples/invalid/invalid_pattern.yml
  buildtest/buildsystem/schemas/global/examples/invalid/maintainers_type_mismatch.yml
  buildtest/buildsystem/schemas/global/examples/invalid/missing-version.yml
  buildtest/buildsystem/schemas/global/examples/valid/examples.yml
  buildtest/buildsystem/schemas/script/examples/1.0/invalid/examples.yml
  buildtest/buildsystem/schemas/script/examples/1.0/valid/examples.yml
  buildtest/buildsystem/schemas/script/script-v1.0.schema.json
  buildtest/executors/base.py
  tests/examples/buildspecs/environment.yml
  tests/examples/buildspecs/python-shell.yml
  tests/examples/buildspecs/shell_examples.yml
  tests/examples/buildspecs/slurm.yml
Labels: size/XL, 🔍 Ready for Review

#337 fix bug in buildtest buildspec find due to "buildspecs" key caused all names to be called "buildspecs"
  buildtest/menu/buildspec.py
Labels: size/XS, 🔍 Ready for Review

#338 update README and index.rst page
  README.rst
  docs/api/buildtest.menu.rst
  docs/api/buildtest.menu.schema.rst
  docs/index.rst
  docs/terminology.rst
Labels: size/M, 🔍 Ready for Review

#339 bug in CompilerBuilder setup method
  buildtest/buildsystem/base.py
Labels: size/S, 🔍 Ready for Review

#340 regenerate doc examples
  buildtest/menu/schema.py
  docs/docgen/buildtest_repo_--help.txt
  docs/docgen/getting_started/buildspec-find.txt
  docs/docgen/getting_started/buildspec-view.txt
  docs/docgen/getting_started/invalid-buildspec.txt
  docs/docgen/getting_started/invalid-executor.txt
  docs/docgen/getting_started/multi-buildspecs.txt
  docs/docgen/schemas/compiler-examples.txt
  docs/docgen/schemas/compiler-json.txt
  docs/docgen/schemas/global-examples.txt
  docs/docgen/schemas/global-json.txt
  docs/docgen/schemas/script-examples.txt
  docs/docgen/schemas/script-json.txt
  docs/docgen/schemas/settings-examples.txt
  docs/docgen/schemas/settings-json.txt
  docs/getting_started.rst
Labels: size/XL, 🔍 Ready for Review

#341 Jobid bug
  .gitignore
  README.rst
  buildtest/executors/base.py
  docs/index.rst
Labels: size/S, 🔍 Ready for Review

#342 make buildtest config edit to validate buildtest settings after closing file
  buildtest/menu/config.py
Labels: size/S, 🔍 Ready for Review

#343 adding buildtest config validate which will validate the buildtest settings file
  buildtest/menu/__init__.py
  buildtest/menu/config.py
  tests/menu/test_config.py
Labels: size/S, 🔍 Ready for Review
