Repository buildtesters/buildtest, pull requests merged in 2020-03, with the labels that each got.

#195 remove images in docs showing build examples.
  docs/build_subcommand/build.rst
  docs/build_subcommand/test.png
  docs/build_subcommand/test_dictionary.png
Labels: 🔍 Ready for Review

#192 remove ModuleCollection class and merge methods into Module()
  .travis.yml
  buildtest/module.py
  examples/collection.py
  tests/test_modules.py
  tests/test_testconfigs.py
Labels: size/L, 🔍 Ready for Review

#197 remove eb installation from Travis. Refactor regression test, removed
  .travis.yml
  buildtest/tools/defaults.py
  tests/test_build.py
  tests/test_config_file.py
  tests/test_inspect.py
  tests/test_modules.py
Labels: size/M, 🔍 Ready for Review

#191 Add/single config argument
  buildtest/docgen/main.py
  buildtest/tools/build.py
  buildtest/tools/buildsystem/singlesource.py
  buildtest/tools/defaults.py
  buildtest/tools/get.py
  buildtest/tools/menu.py
  buildtest/tools/testconfigs.py
  buildtest/tools/writer.py
  docs/api/buildtest.tools.rst
  docs/api/buildtest.tools.testconfigs.rst
  docs/build_subcommand/build.rst
  docs/configuring_buildtest.rst
  docs/docgen/buildtest_testconfigs_-h.txt
  docs/docgen/buildtest_testconfigs_list.txt
  docs/docgen/buildtest_testconfigs_view_tutorial_compilers_args.c.yml
  docs/getting_started.rst
  docs/index.rst
  docs/installing_buildtest.rst
  docs/managing_testconfigs.rst
  tests/test_config_file.py
  tests/test_inspect.py
  tests/test_modules.py
Labels: size/XL, 🔍 Ready for Review

#198 Remove/lmod dependency
  .travis.yml
  CHANGELOG.rst
  buildtest/main.py
  buildtest/spider.py
  buildtest/tools/menu.py
  buildtest/tools/modules.py
  buildtest/tools/modulesystem/collection.py
  buildtest/tools/modulesystem/tree.py
  buildtest/tools/system.py
  buildtest_regtest.py
  docs/installing_buildtest.rst
  docs/spider.rst
  tests/run_tests.sh
  tests/test_config_file.py
  tests/test_modules.py
Labels: size/L, ✅ Approved

#201 cleaning up documentation that references features not available
  buildtest/docgen/main.py
  docs/api/buildtest.module.rst
  docs/api/buildtest.rst
  docs/api/buildtest.spider.rst
  docs/api/modules.rst
  docs/build_subcommand/build-workflow.png
  docs/build_subcommand/build.rst
  docs/build_subcommand/build_concepts.rst
  docs/build_subcommand/build_examples.rst
  docs/build_subcommand/build_status.rst
  docs/build_subcommand/module_collections.rst
  docs/build_subcommand/singlesource_schema.rst
  docs/building_test.rst
  docs/configuring_buildtest.rst
  docs/docgen/default_module_tree.txt
  docs/docgen/tutorial.compilers.args.c.yml.txt
  docs/docgen/tutorial.compilers.args.c.yml_dry.txt
  docs/docgen/tutorial.compilers.args.c.yml_v.txt
  docs/docgen/tutorial.openacc.vecAdd.c.yml.txt
  docs/feature_overview.rst
  docs/getting_started.rst
  docs/index.rst
  docs/introspection.rst
  docs/module_operation.rst
  docs/spider.rst
  docs/what_is_buildtest.rst
Labels: ✅ Approved

#203 add few urls to white list, most of these errors reported by URLcheck…
  .github/workflows/urlchecker.yml
  docs/conf.py
Labels: size/XS, 🔍 Ready for Review

#205 Moving install_deps into testing directory, as it is only used there
  .travis.yml
  tests/install_deps.sh
Labels: ✅ Approved

#207 Removing argcomplete and termcolor, not essential for buildtest
  CHANGELOG.rst
  buildtest/tools/menu.py
  docs/installing_buildtest.rst
  docs/requirements.txt
  setup.py
Labels: size/M, ✅ Approved

#209 reorganizing modules to prepare for test config schema addition - sim…
  buildtest/buildsystem/__init__.py
  buildtest/buildsystem/dry.py
  buildtest/buildsystem/singlesource.py
  buildtest/buildsystem/status.py
  buildtest/buildsystem/writer.py
  buildtest/config.py
  buildtest/defaults.py
  buildtest/docgen/main.py
  buildtest/log.py
  buildtest/main.py
  buildtest/menu/__init__.py
  buildtest/menu/build.py
  buildtest/menu/config.py
  buildtest/menu/get.py
  buildtest/menu/show.py
  buildtest/menu/status.py
  buildtest/system.py
  buildtest/tools/configuration/__init__.py
  buildtest/tools/configuration/config.py
  buildtest/utils/__init__.py
  buildtest/utils/file.py
  tests/test_config_file.py
  tests/test_file.py
  tests/test_inspect.py
Labels: ✅ Approved

#204 updating docs including section on contribution, CHANGELOG, and some …
  CHANGELOG.rst
  CONTRIBUTING.rst
  docs/Pipfile
  docs/configuring_buildtest.rst
  docs/contributing.rst
  docs/contributing/build_documentation.rst
  docs/contributing/github_integration.rst
  docs/contributing/maintainer_guide.rst
  docs/contributing/regression_testing.rst
  docs/contributing/release_process.rst
  docs/contributing/setup.rst
  docs/docgen/buildtest_-h.txt
  docs/docgen/buildtest_build_-h.txt
  docs/docgen/buildtest_config_view.txt
  docs/docgen/buildtest_show_--config.txt
  docs/getting_started.rst
  docs/installing_buildtest.rst
  docs/references.rst
  docs/scripts/build-module-collection-example.txt
  docs/scripts/build-mpi-example.txt
  docs/scripts/buildtest-module-collection-update.txt
Labels: documentation, size/XL, ✅ Approved

#208 updating year to 2020 in LICENSE
  LICENSE
Labels: size/XS, ✅ Approved

#213 moving BuildTestError and BuildTestCommand methods to utils
  buildtest/buildsystem/singlesource.py
  buildtest/docgen/main.py
  buildtest/exceptions.py
  buildtest/log.py
  buildtest/system.py
  buildtest/utils/command.py
  buildtest/utils/file.py
  tests/test_command.py
  tests/test_exceptions.py
  tests/test_file.py
Labels: size/L, ✅ Approved

#214 update maintainer page with pics to branch setting and merge option
  docs/contributing.rst
  docs/contributing/buildtest_branch_settings.png
  docs/contributing/buildtest_merge_options.png
  docs/contributing/maintainer_guide.rst
  docs/contributing/setup.rst
Labels: ✅ Approved

#211 testing urlchecker that has retry
  .github/workflows/urlchecker.yml
  README.rst
  docs/spider.rst
Labels: size/XS, 🔍 Ready for Review

#219 Add script schema
  MANIFEST.in
  buildtest/buildsystem/base.py
  buildtest/buildsystem/dry.py
  buildtest/buildsystem/schemas/__init__.py
  buildtest/buildsystem/schemas/outer.schema.json
  buildtest/buildsystem/schemas/script/script-v0.0.1.schema.json
  buildtest/buildsystem/schemas/utils.py
  buildtest/buildsystem/singlesource.py
  buildtest/buildsystem/status.py
  buildtest/buildsystem/writer.py
  buildtest/defaults.py
  buildtest/docgen/main.py
  buildtest/log.py
  buildtest/menu/__init__.py
  buildtest/menu/build.py
  buildtest/menu/get.py
  buildtest/menu/show.py
  buildtest/system.py
  buildtest/utils/command.py
  docs/api/buildtest.tools.writer.rst
  docs/requirements.txt
  setup.py
  tests/test_buildsystem.py
  tests/test_command.py
  tests/test_exceptions.py
  tests/test_inspect.py
  tests/testdir/slurm-hello.yml
Labels: ✅ Approved

#221 fixing client and running first test for script
  buildtest/buildsystem/base.py
  buildtest/menu/__init__.py
  buildtest/menu/build.py
Labels: size/M, ✅ Approved

#218 reorg regtests based on source file to be tested
  tests/buildsystem/__init__.py
  tests/buildsystem/test_base.py
  tests/menu/__init__.py
  tests/menu/test_config.py
  tests/menu/test_show.py
  tests/test_config_file.py
  tests/test_defaults.py
  tests/test_exceptions.py
  tests/utils/__init__.py
  tests/utils/test_command.py
  tests/utils/test_file.py
Labels: ✅ Approved

#222 Update Regression Test Docs
  buildtest/buildsystem/base.py
  buildtest/log.py
  buildtest/menu/build.py
  buildtest/menu/get.py
  buildtest/system.py
  buildtest/utils/command.py
  docs/conf.py
  docs/contributing/regression_testing.rst
  tests/buildsystem/test_base.py
Labels: documentation, size/L, ✅ Approved

#228 .Several Minor fixes related to documentation warning, and examples directory
  buildtest/buildsystem/base.py
  buildtest/buildsystem/schemas/utils.py
  buildtest/system.py
  docs/contributing/github_integration.rst
  docs/getting_started.rst
  docs/requirements.txt
  examples/script/bzip2.yml
  examples/script/slurm.yml
  examples/script/zlib.yml
  site/benchmark/stream/src/mysecond.c
  site/benchmark/stream/src/stream.c
  site/benchmark/stream/stream.c.yml
Labels: size/L, ✅ Approved

#231 Remove clear build option
  buildtest/menu/__init__.py
  buildtest/menu/build.py
Labels: size/S, ✅ Approved

#233 General fix
  buildtest/buildsystem/base.py
  buildtest/menu/build.py
  examples/script/bzip2.yml
  examples/script/python-circle.yml
Labels: size/L, 🔍 Ready for Review

#232 Generate local testdir by default in present working directory
  buildtest/buildsystem/base.py
  buildtest/menu/__init__.py
  buildtest/menu/build.py
Labels: size/M, ✅ Approved

#234 adding stream benchmark for uniprocess and OpenMP
  examples/benchmarks/stream.yml
Labels: size/S, 🔍 Ready for Review

#235 updating url checker name and version to use latest
  .github/workflows/urlchecker.yml
Labels: size/XS, ✅ Approved

#237 Add config jsonschema
  CONTRIBUTING.rst
  buildtest/buildsystem/base.py
  buildtest/buildsystem/schemas/utils.py
  buildtest/config.py
  buildtest/defaults.py
  buildtest/executors/__init__.py
  buildtest/executors/base.py
  buildtest/menu/__init__.py
  buildtest/menu/config.py
  buildtest/settings.yml
  buildtest/settings/README.md
  buildtest/settings/__init__.py
  buildtest/settings/default.schema.json
  buildtest/settings/default.yml
  docs/contributing/github_integration.rst
  tests/config_schema_examples/combined-example.yml
  tests/config_schema_examples/local-example.yml
  tests/config_schema_examples/slurm-example.yml
  tests/executors/__init__.py
  tests/executors/test_base.py
  tests/menu/test_config.py
  tests/menu/test_show.py
Labels: ✅ Approved

#239 Removing config show for global configuration
  buildtest/menu/__init__.py
  buildtest/menu/config.py
  buildtest/menu/show.py
  tests/menu/test_config.py
Labels: ✅ Approved

#242 Updating Documentation
  .github/issue_label_bot.yaml
  README.rst
  buildtest/docgen/main.py
  docs/configuring_buildtest.rst
  docs/contributing/github_integration.rst
  docs/docgen/buildtest_show_--config.txt
  docs/index.rst
  docs/introspection.rst
  docs/references.rst
  docs/spider.rst
Labels: ✅ Approved

#244 Adding zenodo.json to devel
  .zenodo.json
Labels: size/S, ✅ Approved

#248 Need to add sys.path before import from buildtest this Fix #247
  docs/api/buildtest.buildsystem.base.rst
  docs/api/buildtest.buildsystem.rst
  docs/api/buildtest.buildsystem.schemas.rst
  docs/api/buildtest.buildsystem.schemas.utils.rst
  docs/api/buildtest.config.rst
  docs/api/buildtest.defaults.rst
  docs/api/buildtest.exceptions.rst
  docs/api/buildtest.executors.base.rst
  docs/api/buildtest.executors.rst
  docs/api/buildtest.log.rst
  docs/api/buildtest.menu.build.rst
  docs/api/buildtest.menu.config.rst
  docs/api/buildtest.menu.get.rst
  docs/api/buildtest.menu.rst
  docs/api/buildtest.menu.show.rst
  docs/api/buildtest.menu.status.rst
  docs/api/buildtest.rst
  docs/api/buildtest.settings.rst
  docs/api/buildtest.system.rst
  docs/api/buildtest.tools.buildsystem.dry.rst
  docs/api/buildtest.tools.buildsystem.rst
  docs/api/buildtest.tools.buildsystem.singlesource.rst
  docs/api/buildtest.tools.buildsystem.status.rst
  docs/api/buildtest.tools.config.rst
  docs/api/buildtest.tools.configuration.config.rst
  docs/api/buildtest.tools.log.rst
  docs/api/buildtest.tools.rst
  docs/api/buildtest.tools.system.rst
  docs/api/buildtest.utils.command.rst
  docs/api/buildtest.utils.file.rst
  docs/api/buildtest.utils.rst
  docs/api/modules.rst
  docs/conf.py
Labels: size/L, ✅ Approved

#250 remove option buildtest build report.
  buildtest/defaults.py
  buildtest/docgen/main.py
  buildtest/menu/__init__.py
  buildtest/menu/build.py
  buildtest/menu/status.py
  docs/docgen/build-report.txt
  setup.py
Labels: size/M, ✅ Approved
