Repository buildtesters/buildtest, pull requests merged in 2020-08, with the labels that each got.

#402 install with pip not python setup.py install
  MANIFEST.in
  docs/installing_buildtest.rst
  setup.py
Labels: size/S, 🔍 Ready for Review

#403 change startup behavior of buildtest and add tutorials to search path.
  .coveragerc
  buildtest/config.py
  buildtest/defaults.py
  buildtest/executors/base.py
  buildtest/main.py
  buildtest/menu/__init__.py
  buildtest/menu/build.py
  buildtest/menu/buildspec.py
  buildtest/menu/config.py
  buildtest/menu/repo.py
  buildtest/menu/schema.py
  tests/menu/test_config.py
  tests/test_config.py
Labels: size/L, 🔍 Ready for Review

#404 remove buildtest config reset from docs
  buildtest/docgen/main.py
  docs/configuring_buildtest.rst
  docs/docgen/buildtest_schema_--help.txt
  docs/docgen/config-reset.txt
  docs/docgen/config-summary.txt
  docs/docgen/config-validate.txt
  docs/docgen/schemas/compiler-examples.txt
  docs/docgen/schemas/compiler-json.txt
  docs/docgen/schemas/global-examples.txt
  docs/docgen/schemas/global-json.txt
  docs/docgen/schemas/script-examples.txt
  docs/docgen/schemas/script-json.txt
  docs/docgen/schemas/settings-examples.txt
  docs/docgen/schemas/settings-json.txt
  docs/introspection.rst
Labels: size/L, 🔍 Ready for Review

#405 remove buildtest repo command. Remove reference from docs and examples.
  buildtest/defaults.py
  buildtest/docgen/main.py
  buildtest/main.py
  buildtest/menu/__init__.py
  buildtest/menu/build.py
  buildtest/menu/buildspec.py
  buildtest/menu/config.py
  buildtest/menu/repo.py
  buildtest/settings/config.yml
  docs/docgen/buildtest_repo_--help.txt
  docs/getting_started.rst
  docs/introspection.rst
  tests/menu/test_build.py
  tests/menu/test_buildspec.py
  tests/menu/test_repo.py
Labels: size/XL, 🔍 Ready for Review

#406 add buildspec_roots key in [config][paths] to specify root of buildspec
  .github/workflows/buildtest_tutorials.yml
  buildtest/config.py
  buildtest/menu/buildspec.py
  buildtest/menu/config.py
  buildtest/schemas/utils.py
  buildtest/settings/settings.schema.json
  docs/schemas/compiler.rst
  docs/schemas/global.rst
  docs/schemas/script.rst
Labels: size/L, 🔍 Ready for Review

#407 regenerate requirements.txt and update to setup.py
  .github/workflows/buildtest_tutorials.yml
  MANIFEST.in
  docs/installing_buildtest.rst
  docs/requirements.txt
  setup.py
Labels: size/M, 🔍 Ready for Review

#408 move Slurm and LSF Executor docs to batch_support.rst
  buildtest/schemas/settings/examples/valid/combined_executor.yml
  buildtest/schemas/settings/examples/valid/lsf-executor.yml
  buildtest/schemas/settings/examples/valid/slurm-executor.yml
  buildtest/schemas/settings/examples/valid/ssh-executor.yml
  docs/configuring_buildtest.rst
  docs/getting_started.rst
  docs/schemas.rst
  docs/schemas/batch_support.rst
  docs/schemas/writing_buildspecs.rst
Labels: 🔍 Ready for Review

#409 fix bugs reported by travis
  .github/workflows/urlchecker.yml
  buildtest/menu/buildspec.py
  buildtest/schemas/utils.py
  tests/buildsystem/test_base.py
  tests/executors/test_base.py
  tests/menu/test_buildspec.py
  tests/menu/test_config.py
  tests/menu/test_report.py
  tests/schemas/test_utils.py
Labels: size/M, 🔍 Ready for Review

#410 buildspec roots documentation
  buildtest/defaults.py
  buildtest/main.py
  buildtest/menu/build.py
  buildtest/menu/buildspec.py
  docs/configuring_buildtest.rst
  docs/requirements.txt
Labels: size/M, 🔍 Ready for Review

#411 documentation for OpenMP, MPI. add executor name in test directory
  buildtest/buildsystem/base.py
  buildtest/menu/buildspec.py
  docs/schemas/compiler.rst
Labels: size/L, 🔍 Ready for Review

#412 add --tags option in buildtest build. Build tests using tags
  buildtest/defaults.py
  buildtest/menu/__init__.py
  buildtest/menu/build.py
  buildtest/menu/buildspec.py
  tests/menu/test_build.py
  tutorials/compilers/passing_args.yml
  tutorials/environment.yml
  tutorials/invalid_buildspec_section.yml
  tutorials/invalid_executor.yml
  tutorials/pass_returncode.yml
  tutorials/python-shell.yml
  tutorials/selinux.yml
  tutorials/shell_examples.yml
  tutorials/skip_tests.yml
  tutorials/vars.yml
Labels: size/M, 🔍 Ready for Review

#414 add example section for building by tags
  docs/api.rst
  docs/configuring_buildtest.rst
  docs/getting_started.rst
  docs/index.rst
  docs/what_is_buildtest.rst
Labels: size/L, 🔍 Ready for Review

#415 Fix typo
  docs/terminology.rst
Labels: documentation, size/XS, 🔍 Ready for Review

#416 sync schemas from buildtesters/schemas repo
  buildtest/defaults.py
  buildtest/schemas/compiler-v1.0.schema.json
  buildtest/schemas/compiler/compiler-v1.0.schema.json
  buildtest/schemas/defaults.py
  buildtest/schemas/global.schema.json
  buildtest/schemas/python-v1.0.schema.json
  buildtest/schemas/script-v1.0.schema.json
  buildtest/schemas/script/script-v1.0.schema.json
  buildtest/schemas/settings.schema.json
  buildtest/schemas/utils.py
  buildtest/settings/README.md
  docs/schemas.rst
  docs/terminology.rst
Labels: 🔍 Ready for Review

#417 Pre & Post field for build and run section in compiler schemas
  buildtest/buildsystem/base.py
  docs/configuring_buildtest.rst
  docs/schemas/compiler.rst
  docs/schemas/global.rst
  docs/schemas/script.rst
  tutorials/compilers/intel_hello.yml
  tutorials/compilers/pre_post_build_run.yml
Labels: size/L, 🔍 Ready for Review

#419 bump 2 to 5 second for jobid retrieval from Slurm
  buildtest/executors/base.py
Labels: size/XS, 🔍 Ready for Review

#420 add diagrams and builder.rst page
  docs/_static/BuildExecutor.jpg
  docs/_static/BuildspecParser.jpg
  docs/_static/DiscoverBuildspecs.jpg
  docs/_static/GeneralPipeline.jpg
  docs/builder.rst
  docs/configuring_buildtest.rst
  docs/getting_started.rst
  docs/index.rst
Labels: 🔍 Ready for Review

#426 add LSF JobName, output, error into jobscript. Fix lsf executor validate bug
  buildtest/buildsystem/base.py
  buildtest/config.py
  buildtest/executors/lsf.py
Labels: size/S, 🔍 Ready for Review

#428 add before_script and after_script in executor section for schema
  buildtest/buildsystem/base.py
  buildtest/defaults.py
  buildtest/executors/setup.py
  buildtest/menu/build.py
  buildtest/schemas/examples/settings.schema.json/valid/local-executor.yml
  buildtest/schemas/examples/settings.schema.json/valid/lsf-example.yml
  buildtest/schemas/examples/settings.schema.json/valid/lsf-executor.yml
  buildtest/schemas/examples/settings.schema.json/valid/slurm-example.yml
  buildtest/schemas/examples/settings.schema.json/valid/slurm-executor.yml
  buildtest/schemas/examples/settings.schema.json/valid/ssh-executor-example.yml
  buildtest/schemas/settings.schema.json
Labels: size/L, 🔍 Ready for Review

#431 use subprocess instead of BuildTestCommand to get output of all doc
  buildtest/docgen/main.py
  buildtest/menu/build.py
  docs/configuring_buildtest.rst
  docs/docgen/buildtest_--help.txt
  docs/docgen/buildtest_build_--help.txt
  docs/docgen/buildtest_buildspec_--help.txt
  docs/docgen/buildtest_config_--help.txt
  docs/docgen/buildtest_report_--help.txt
  docs/docgen/buildtest_schema_--help.txt
  docs/docgen/compiler_schema/gnu_hello.txt
  docs/docgen/compiler_schema/intel_hello.yml
  docs/docgen/compiler_schema/vecadd.txt
  docs/docgen/getting_started/buildspec-abspath.txt
  docs/docgen/getting_started/buildspec-directory.txt
  docs/docgen/getting_started/buildspec-find.txt
  docs/docgen/getting_started/buildspec-view.txt
  docs/docgen/getting_started/invalid-buildspec.txt
  docs/docgen/getting_started/invalid-executor.txt
  docs/docgen/getting_started/multi-buildspecs.txt
  docs/docgen/getting_started/stage_build.txt
  docs/docgen/getting_started/stage_parse.txt
  docs/docgen/getting_started/tags.txt
  docs/docgen/schemas/avail-schemas.txt
  docs/docgen/schemas/compiler-examples.txt
  docs/docgen/schemas/compiler-json.txt
  docs/docgen/schemas/global-examples.txt
  docs/docgen/schemas/global-json.txt
  docs/docgen/schemas/gnu_hello.txt
  docs/docgen/schemas/gnu_hello.yml
  docs/docgen/schemas/pass_returncode.txt
  docs/docgen/schemas/passing_args.yml
  docs/docgen/schemas/pre_post_build_run.yml
  docs/docgen/schemas/script-examples.txt
  docs/docgen/schemas/script-json.txt
  docs/docgen/schemas/settings-examples.txt
  docs/docgen/schemas/settings-json.txt
  docs/docgen/schemas/skip_tests.txt
  docs/docgen/schemas/vecadd.txt
  docs/docgen/schemas/vecadd.yml
  docs/schemas/compiler.rst
  docs/schemas/writing_buildspecs.rst
Labels: 🔍 Ready for Review

#432 add Parser Schema Validationg Diagram
  docs/_static/ParserSchemaValidationDiagram.png
  docs/builder.rst
  docs/schemas/global.rst
  docs/schemas/writing_buildspecs.rst
Labels: 🔍 Ready for Review

#433 Fixups
  buildtest/buildsystem/base.py
  buildtest/executors/local.py
  buildtest/executors/slurm.py
  buildtest/menu/buildspec.py
  tutorials/compilers/pre_post_build_run.yml
  tutorials/compilers/vecadd.yml
  tutorials/systemd.yml
Labels: size/S, 🔍 Ready for Review

#434 move shebang, sbatch and bsub lines outside of method generate_script
  buildtest/buildsystem/base.py
Labels: size/M, 🔍 Ready for Review

#435 Update CHANGELOG.rst
  CHANGELOG.rst
Labels: size/M

#436 remove files that shouldnt be commited to upstream.
  docs/Pipfile
  docs/buildspec.error
  docs/docgen/gettingstarted-example1.txt
Labels: size/L, 🔍 Ready for Review

#438 add builder.metadata["jobid"] once jobID retrieved from SlurmExecutor
  buildtest/executors/slurm.py
Labels: size/S, 🔍 Ready for Review

#439 Fix lsfexecutor
  buildtest/executors/lsf.py
  buildtest/executors/slurm.py
Labels: size/M, 🔍 Ready for Review
