Repository buildtesters/buildtest, pull requests merged in 2022-06, with the labels that each got.

#1064 rename 'numprocs' to 'poolsize' property in settings schema
  buildtest/executors/setup.py
  buildtest/schemas/examples/settings.schema.json/valid/cobalt-example.yml
  buildtest/schemas/examples/settings.schema.json/valid/combined_executor.yml
  buildtest/schemas/examples/settings.schema.json/valid/local-executor.yml
  buildtest/schemas/examples/settings.schema.json/valid/lsf-example.yml
  buildtest/schemas/examples/settings.schema.json/valid/pbs-example.yml
  buildtest/schemas/examples/settings.schema.json/valid/slurm-example.yml
  buildtest/schemas/settings.schema.json
  buildtest/settings/config.yml
  docs/configuring_buildtest/overview.rst
Labels: size/M

#1066 Update urlchecker.yml
  .github/workflows/urlchecker.yml
Labels: size/XS

#1069 [WIP] Add summary field to schema
  buildtest/schemas/compiler.schema.json
  buildtest/schemas/definitions.schema.json
  buildtest/schemas/examples/script.schema.json/invalid/examples.yml
  buildtest/schemas/examples/script.schema.json/valid/examples.yml
  buildtest/schemas/script.schema.json
  buildtest/schemas/spack.schema.json
  tutorials/summary_example.yml
Labels: size/M

#1071 update CHANGELOG
  CHANGELOG.rst
Labels: size/XS

#1074 add new command 'buildtest stats'
  bash_completion.sh
  buildtest/cli/__init__.py
  buildtest/cli/clean.py
  buildtest/cli/stats.py
  buildtest/main.py
  docs/features.rst
Labels: size/L

#1079 add Parser Diagram
  docs/_static/ParserDiagram.png
  docs/builder.rst
Labels: size/XS

#1081 Rename commands to buildtest buildspec edit-test and buildtest buildspec edit-file
  .gitignore
  bash_completion.sh
  buildtest/cli/__init__.py
  docs/gettingstarted/buildspecs_interface.rst
Labels: size/M

#1083 refactor 'buildtest cdash' and add option buildtest cdash upload --open
  bash_completion.sh
  buildtest/cli/__init__.py
  buildtest/cli/cdash.py
  buildtest/main.py
  tests/cli/test_cdash.py
Labels: size/L

#1082 Sort report by time
  bash_completion.sh
  buildtest/cli/__init__.py
  buildtest/cli/report.py
  docs/gettingstarted/query_test_report.rst
  tests/cli/test_report.py
Labels: size/L

#1086 update bash completion and add aliases
  bash_completion.sh
  buildtest/cli/__init__.py
  buildtest/main.py
Labels: size/S

#1087 fix bugs reported by documentation build
  docs/contributing/regression_testing.rst
  docs/features.rst
  docs/gettingstarted/buildspecs_interface.rst
  docs/gettingstarted/query_test_report.rst
Labels: size/M

#1093 add command buildtest buildspec maintainers
  bash_completion.sh
  buildtest/cli/__init__.py
  buildtest/cli/buildspec.py
  buildtest/cli/help.py
  buildtest/main.py
  docs/gettingstarted/buildspecs_interface.rst
  tests/cli/test_buildspec.py
Labels: size/L

#1094 update urlchecker workflow
  .github/workflows/urlchecker.yml
Labels: size/XS

#1096 Support for aliases in 'buildtest help' subcommands
  bash_completion.sh
  buildtest/cli/__init__.py
  buildtest/cli/help.py
Labels: size/S

#1097 Allow dash char
  buildtest/schemas/examples/global.schema.json/valid/examples.yml
  buildtest/schemas/global.schema.json
Labels: size/S

#1098 Remove executor check during Parse Stage
  buildtest/buildsystem/parser.py
  buildtest/cli/build.py
  tests/buildsystem/test_base.py
Labels: size/M

#1105 update changelog
  CHANGELOG.rst
Labels: size/XS

#1106 update section for test names section that includes a dash
  docs/buildspecs/global.rst
Labels: size/S

#1108 add build stamp "-Experimental" in CDASH upload
  buildtest/cli/cdash.py
Labels: size/XS

#1109 add summary property in report file and CDASH upload
  buildtest/builders/base.py
  buildtest/cli/build.py
  buildtest/cli/cdash.py
Labels: size/S

#1110 Remove urlchecker cron workflow
  .github/workflows/urlcheck_cron.yml
  .github/workflows/urlchecker.yml
  README.rst
Labels: size/M

#1116 dont raise error when setting invalid editor value
  buildtest/tools/editor.py
  tests/tools/test_editor.py
Labels: size/S

#1117 update installation workflow
  .github/workflows/installation.yml
Labels: size/XS

#1118 remove exclusion for py3.8 and 3.9 for macos
  .github/workflows/regression.yml
Labels: size/XS

#1119 downgrade version for mirroring workflow to 0.2
  .github/workflows/mirror.yml
Labels: size/XS

#1120 add coverage for ubuntu-22.04 and macos-12 in regression test
  .github/workflows/regression.yml
Labels: size/XS

#1122 Add methods to randomly select names and builders from Report class
  buildtest/cli/report.py
  tests/cli/test_inspect.py
Labels: size/M

#1124 fix regression test for 'buildtest --editor'
  buildtest/tools/editor.py
  tests/tools/test_editor.py
Labels: size/L

#1125 update changelog
  CHANGELOG.rst
Labels: size/S

#1121 add regression test for buildtest stats
  buildtest/cli/stats.py
  tests/test_stats.py
Labels: size/M

#1127 regenerate documentation example for buildtest tutorial
  docs/buildtest_tutorial_examples/compilers/build/compiler_exclude.txt
  docs/buildtest_tutorial_examples/compilers/build/compiler_status_regex.txt
  docs/buildtest_tutorial_examples/compilers/build/custom_run.txt
  docs/buildtest_tutorial_examples/compilers/build/envvar_override.txt
  docs/buildtest_tutorial_examples/compilers/build/gnu_hello_c.txt
  docs/buildtest_tutorial_examples/compilers/build/gnu_hello_fortran.txt
  docs/buildtest_tutorial_examples/compilers/build/openmp_hello.txt
  docs/buildtest_tutorial_examples/compilers/build/pre_post_build_run.txt
  docs/buildtest_tutorial_examples/compilers/build/stream_example.txt
  docs/buildtest_tutorial_examples/compilers/build/stream_example_metrics.txt
  docs/buildtest_tutorial_examples/compilers/build/vecadd.txt
  docs/buildtest_tutorial_examples/compilers/inspect/compiler_status_regex.txt
  docs/buildtest_tutorial_examples/compilers/inspect/custom_run.txt
  docs/buildtest_tutorial_examples/compilers/inspect/envvar_override.txt
  docs/buildtest_tutorial_examples/compilers/inspect/gnu_hello_c.txt
  docs/buildtest_tutorial_examples/compilers/inspect/gnu_hello_fortran.txt
  docs/buildtest_tutorial_examples/compilers/inspect/openmp_hello.txt
  docs/buildtest_tutorial_examples/compilers/inspect/pre_post_build_run.txt
  docs/buildtest_tutorial_examples/compilers/inspect/stream_example.txt
  docs/buildtest_tutorial_examples/compilers/inspect/stream_openmp_metrics.txt
  docs/buildtest_tutorial_examples/spack/build/env_create_directory.txt
  docs/buildtest_tutorial_examples/spack/build/env_create_manifest.txt
  docs/buildtest_tutorial_examples/spack/build/env_install.txt
  docs/buildtest_tutorial_examples/spack/build/install_specs.txt
  docs/buildtest_tutorial_examples/spack/build/mirror_example.txt
  docs/buildtest_tutorial_examples/spack/build/pre_post_cmds.txt
  docs/buildtest_tutorial_examples/spack/build/remove_environment_example.txt
  docs/buildtest_tutorial_examples/spack/build/spack_sbatch.txt
  docs/buildtest_tutorial_examples/spack/build/spack_test.txt
  docs/buildtest_tutorial_examples/spack/build/spack_test_specs.txt
  docs/buildtest_tutorial_examples/spack/inspect/env_create_directory.txt
  docs/buildtest_tutorial_examples/spack/inspect/env_create_manifest.txt
  docs/buildtest_tutorial_examples/spack/inspect/env_install.txt
  docs/buildtest_tutorial_examples/spack/inspect/install_specs.txt
  docs/buildtest_tutorial_examples/spack/inspect/mirror_example.txt
  docs/buildtest_tutorial_examples/spack/inspect/pre_post_cmds.txt
  docs/buildtest_tutorial_examples/spack/inspect/remove_environment_example.txt
  docs/buildtest_tutorial_examples/spack/inspect/spack_sbatch.txt
  docs/buildtest_tutorial_examples/spack/inspect/spack_test.txt
  docs/buildtest_tutorial_examples/spack/inspect/spack_test_specs.txt
Labels: size/XXL

#1129 increase coverage of buildtest installation to ubuntu-22.04 and macos-12
  .github/workflows/installation.yml
Labels: size/XS

#1131 bump version of black in pre-commit-config.yaml
  .pre-commit-config.yaml
Labels: size/XS

#1130 limit output of buildtest report
  bash_completion.sh
  buildtest/cli/__init__.py
  buildtest/cli/help.py
  buildtest/cli/report.py
  docs/gettingstarted/query_test_report.rst
  tests/cli/test_report.py
Labels: size/M

#1133 fix bug in 'buildtest buildspec edit-test'
  buildtest/main.py
Labels: size/XS

#1134 fixed broken links in the documentation according to issue 1103
  docs/batch_support.rst
  docs/configuring_buildtest/overview.rst
Labels: size/XS

#1136 update changelog
  CHANGELOG.rst
Labels: size/XS

#1135 add option 'buildtest buildspec find --quiet'
  bash_completion.sh
  buildtest/cli/__init__.py
  buildtest/cli/buildspec.py
  buildtest/cli/help.py
  docs/gettingstarted/buildspecs_interface.rst
  tests/cli/test_buildspec.py
Labels: size/L

#1138 Rewrite documentation for invalid examples
  docs/batch_support.rst
  docs/buildtest_site.rst
  docs/configuring_buildtest/overview.rst
  docs/configuring_buildtest/site_examples.rst
  docs/facility_examples.rst
Labels: size/XXL
