Repository buildtesters/buildtest, pull requests merged in 2022-10, with the labels that each got.

#1249 Added option to limit row count using "buildtest report --row-count"
  bash_completion.sh
  buildtest/cli/__init__.py
  buildtest/cli/help.py
  buildtest/cli/report.py
  docs/gettingstarted/query_test_report.rst
  tests/cli/test_report.py
Labels: size/M

#1258 add option 'buildtest history list --color' to colorize output of history table
  bash_completion.sh
  buildtest/cli/__init__.py
  buildtest/cli/help.py
  buildtest/cli/history.py
  tests/cli/test_history.py
Labels: size/M

#1239 Add positional argument to test specific compilers
  bash_completion.sh
  buildtest/cli/__init__.py
  buildtest/cli/compilers.py
  docs/configuring_buildtest/compilers.rst
  tests/settings/ascent.yml
  tests/test_ascent.py
Labels: size/L

#1259 don't raise exception with 'buildtest buildspec show'
  buildtest/cli/buildspec.py
  buildtest/cli/compilers.py
  tests/cli/test_buildspec.py
  tests/test_ascent.py
Labels: size/M

#1260 Add subcommand "buildtest report path" to print path to the report file being used.
  bash_completion.sh
  buildtest/cli/__init__.py
  buildtest/cli/help.py
  buildtest/cli/report.py
  docs/gettingstarted/query_test_report.rst
  tests/cli/test_report.py
Labels: size/M

#1263 update documentation with dropdown in several pages
  buildtest/cli/compilers.py
  docs/configuring_buildtest/compilers.rst
  docs/configuring_buildtest/site_examples.rst
  docs/contributing/code_contribution_guide.rst
  docs/contributing/schema.rst
  docs/facility_examples.rst
  docs/features.rst
Labels: size/XXL

#1265 add support to skip buildspec via 'skip' property
  buildtest/buildsystem/builders.py
  buildtest/schemas/global.schema.json
  docs/buildspecs/buildspec_overview.rst
  tests/cli/test_build.py
  tutorials/skip_buildspec.yml
Labels: size/M

#1267 Remove Spell Check CI
  .github/workflows/spellcheck.yml
  .spellcheck.yml
  .wordlist.txt
Labels: size/M

#1268 update batch documentation to use dropdowns
  docs/batch_support.rst
  docs/configuring_buildtest/site_examples.rst
Labels: size/XL

#1270 add support for Programming Environment in buildtest configuration
  buildtest/cli/compilers.py
  buildtest/schemas/settings.schema.json
  docs/configuring_buildtest/compilers.rst
  tests/settings/ascent.yml
  tests/settings/cori.yml
  tests/test_cori.py
Labels: size/L

#1269 Update changelog
  CHANGELOG.rst
Labels: size/S

#1271 add property 'purge' in buildtest configuration
  buildtest/cli/compilers.py
  buildtest/schemas/settings.schema.json
  docs/configuring_buildtest/compilers.rst
Labels: size/L

#1272 buildtest 1.0 release
  CHANGELOG.rst
  buildtest/__init__.py
Labels: size/XS

#1277 Add option buildtest --helpcolor to show available color options in table format
  bash_completion.sh
  buildtest/cli/__init__.py
  buildtest/cli/helpcolor.py
  buildtest/main.py
  docs/features.rst
  tests/cli/test_helpcolor.py
Labels: size/M

#1280 Added top level argument color option "buildtest --color"
  bash_completion.sh
  buildtest/cli/__init__.py
  buildtest/cli/help.py
  docs/features.rst
  docs/gettingstarted/buildspecs_interface.rst
  docs/gettingstarted/query_test_report.rst
Labels: size/M

#1282 Follow-Up Merge request to PR #1280 (https://github.com/buildtesters/buildtest/pull/1280 )
  buildtest/cli/report.py
Labels: size/S

#1283 testing buildtest compilers with module load testing will honor 'purge' property
  buildtest/cli/compilers.py
  docs/configuring_buildtest/compilers.rst
Labels: size/M

#1285 Redesign buildtest documentation based on divio
  docs/builder.rst
  docs/buildspecs/buildspec_overview.rst
  docs/configuring_buildtest.rst
  docs/gettingstarted/buildingtest.rst
  docs/index.rst
  docs/schema_examples.rst
Labels: size/L

#1284 Added color output for buildtest buildspec maintainers option
  buildtest/cli/buildspec.py
  buildtest/main.py
  tests/cli/test_buildspec.py
Labels: size/M

#1286 increase length of test names to 48 characters
  buildtest/schemas/examples/global.schema.json/invalid/exceed_testname_length.yml
  buildtest/schemas/global.schema.json
  docs/buildspecs/global.rst
Labels: size/S

#1287 Colorized output for buildtest inspect list command
  buildtest/cli/inspect.py
  tests/cli/test_inspect.py
Labels: size/S

#1288 update documentation on what is buildtest
  docs/index.rst
Labels: size/S
