Repository buildtesters/buildtest, pull requests merged in 2022-12, with the labels that each got.

#1305 add useful links on left side bar in user docs
  docs/index.rst
Labels: size/XS

#1306 use communityinviter for slack invites instead of heroku
  README.rst
  docs/contributing/new_maintainer_checklist.rst
  docs/index.rst
Labels: size/XS

#1299 Add coverage for buildtest report clear
  buildtest/cli/report.py
  tests/cli/test_report.py
Labels: size/S

#1308 fix bug in 'buildtest bc edit' where test were not opening in editor
  buildtest/cli/buildspec.py
  tests/cli/test_buildspec.py
Labels: size/S

#1307 Add option "buildtest tutorial-examples" to auto-generate documentation examples for Buildtest Tutorial
  bash_completion.sh
  buildtest/cli/__init__.py
  buildtest/cli/help.py
  buildtest/main.py
  buildtest/tools/tutorialexamples.py
  docs/contributing/build_documentation.rst
  tests/tools/test_tutorialexamples.py
Labels: size/M

#1309 Update logic for Buildspec Parser to incorporate executor check
  buildtest/buildsystem/parser.py
  buildtest/cli/build.py
  buildtest/cli/buildspec.py
  buildtest/exceptions.py
  buildtest/utils/file.py
  tests/buildsystem/test_base.py
Labels: size/L

#1312 Add loglevel option to filter logs (buildtest --loglevel)
  bash_completion.sh
  buildtest/cli/__init__.py
  buildtest/cli/build.py
  buildtest/cli/buildspec.py
  buildtest/config.py
  buildtest/log.py
  buildtest/main.py
  buildtest/system.py
Labels: size/M

#1313 add support for assert greater equal. Update metrics property
  buildtest/builders/base.py
  buildtest/schemas/definitions.schema.json
  docs/buildspecs/buildspec_overview.rst
  tests/builders/assert_ge.yml
  tests/builders/test_builders.py
  tutorials/stream.yml
Labels: size/L

#1320 Add support for Assert Equality
  buildtest/builders/base.py
  buildtest/executors/base.py
  buildtest/schemas/definitions.schema.json
  buildtest/schemas/examples/script.schema.json/valid/examples.yml
  docs/buildspecs/buildspec_overview.rst
  tests/builders/assert_eq.yml
  tests/builders/assert_ge.yml
  tests/builders/test_builders.py
  tutorials/metrics_regex.yml
  tutorials/perf_checks/assert_eq.yml
  tutorials/perf_checks/assert_eq_exceptions.yml
Labels: size/L

#1322 update black version in .pre-commit-config.yaml
  .pre-commit-config.yaml
Labels: size/XS

#1323 rearrange content of Buildspec Overview into several sub-pages
  docs/buildspec_tutorial.rst
  docs/buildspecs/buildspec_overview.rst
  docs/buildspecs/customize_shell.rst
  docs/buildspecs/global.rst
  docs/buildspecs/multi_executor.rst
  docs/buildspecs/performance_checks.rst
  docs/buildspecs/test_dependency.rst
Labels: size/XL

#1324 fix regression test with validating module tool on cori and ascent
  tests/test_ascent.py
  tests/test_cori.py
Labels: size/S
