Repository buildtesters/buildtest, pull requests merged in 2022-11, with the labels that each got.

#1290 minor output change to buildtest build command
  bash_completion.sh
  buildtest/cli/build.py
Labels: size/L

#1294 Update link for SC22 talk
  docs/references.rst
Labels: size/XS

#1298 Color the output of "buildtest buildspec summary"
  buildtest/cli/buildspec.py
  buildtest/main.py
  tests/cli/test_buildspec.py
Labels: size/M
