Repository buildtesters/buildtest, pull requests merged in 2022-08, with the labels that each got.

#1170 Changed report to print failures in red and passes in Red
  buildtest/cli/report.py
  tests/cli/test_report.py
Labels: size/M

#1180 mutually exclusive option for buildtest report --passed and --failure option
  buildtest/cli/__init__.py
  docs/gettingstarted/query_test_report.rst
Labels: size/S

#1181 remove nersc mirroring workflow
  .github/workflows/mirror.yml
Labels: size/S

#1175 Automatically test compiler instances via module load test
  bash_completion.sh
  buildtest/cli/__init__.py
  buildtest/cli/compilers.py
  buildtest/cli/help.py
  docs/configuring_buildtest/compilers.rst
  tests/test_cori.py
Labels: size/L

#1143 add regression test for editing buildspecs
  .gitignore
  buildtest/cli/buildspec.py
  tests/cli/test_buildspec.py
Labels: size/M

#1182 raised non-zero return code
  buildtest/cli/buildspec.py
Labels: size/XS

#1188 change behavior of 'buildtest config compilers find'
  buildtest/cli/compilers.py
Labels: size/S

#1176 add support for detailed summary via 'buildtest report summary --detailed'
  bash_completion.sh
  buildtest/cli/__init__.py
  buildtest/cli/report.py
  docs/gettingstarted/query_test_report.rst
  tests/cli/test_report.py
Labels: size/L

#1193 Fixed CI test failing
  buildtest/cli/buildspec.py
  tests/cli/test_buildspec.py
Labels: size/M

#1198 need to run 'module -t av' in a subshell
  buildtest/cli/compilers.py
Labels: size/XS

#1197 Fixed the case when there no invalid buildspecs at all
  buildtest/cli/buildspec.py
  tests/cli/test_buildspec.py
Labels: size/M

#1200 rename option --debug to --detailed for 'buildtest cg compilers find'
  bash_completion.sh
  buildtest/cli/__init__.py
  buildtest/cli/compilers.py
Labels: size/M

#1202 enable soft wrap when using rich console
  buildtest/defaults.py
Labels: size/XS

#1203 Fix tables wrapping for 'buildtest buildspec' command
  buildtest/cli/buildspec.py
Labels: size/L

#1189 Testing compilers fix bug
  buildtest/cli/compilers.py
Labels: size/M

#1195 Remove --pager option from buildtest report summary
  .gitignore
  bash_completion.sh
  buildtest/cli/__init__.py
  buildtest/cli/report.py
  tests/cli/test_report.py
Labels: size/M

#1205 Specify MODULEPATH when searching for compilers
  bash_completion.sh
  buildtest/cli/__init__.py
  buildtest/cli/compilers.py
  buildtest/schemas/settings.schema.json
  buildtest/settings/config.yml
Labels: size/M

#1209 updating CHANGELOG
  CHANGELOG.rst
Labels: size/S

#1212 update 'buildtest help' output
  buildtest/cli/help.py
Labels: size/XS
