Repository buildtesters/buildtest, pull requests merged in 2022-07, with the labels that each got.

#1139 v0.15.0 release
  buildtest/__init__.py
  docs/what_is_buildtest.rst
Labels: size/XS

#1140 buildtest report --pass
  bash_completion.sh
  buildtest/cli/__init__.py
  buildtest/cli/help.py
  buildtest/cli/report.py
  docs/gettingstarted/query_test_report.rst
  tests/cli/test_report.py
Labels: size/M

#1141 fix Slurm Job State bug when submit request
  buildtest/builders/base.py
Labels: size/XS

#1147 update black version in pre-commit configuration and pass --verbose in CI check
  .github/workflows/black.yml
  .pre-commit-config.yaml
Labels: size/XS

#1148 BuildTestCommand requires input argument is passed
  buildtest/utils/command.py
  tests/utils/test_command.py
Labels: size/M

#1149 Issue uploading results to CodeCov
  .github/workflows/regression.yml
Labels: size/XS

#1155 add new command 'buildtest info'
  bash_completion.sh
  buildtest/cli/__init__.py
  buildtest/cli/info.py
  buildtest/main.py
  docs/features.rst
  tests/cli/test_info.py
Labels: size/L

#1157 Fix ModuleNotFoundError: No module named 'buildtest'
  buildtest/tools/unittests.py
Labels: size/XS

#1153 add slides for PEARC22 conference
  docs/references.rst
Labels: size/XS

#1161 testing external pull request event for Cori
  .gitlab/cori.yml
Labels: size/XS

#1163 add pager support for buildtest buildspec summary
  bash_completion.sh
  buildtest/cli/__init__.py
  buildtest/cli/buildspec.py
  buildtest/cli/help.py
  buildtest/main.py
  tests/cli/test_buildspec.py
Labels: size/M

#1162 trigger based on external pull request event for ascent
  .gitlab/olcf.yml
Labels: size/XS

#1169 Added feature buildtest --lastlog-path
  bash_completion.sh
  buildtest/cli/__init__.py
  buildtest/main.py
Labels: size/XS

#1168 Renamed buildtest --lastlog in the codebase
  bash_completion.sh
  buildtest/cli/__init__.py
  buildtest/main.py
Labels: size/XS

#1167 Added feature buildtest --print-lastlog
  bash_completion.sh
  buildtest/cli/__init__.py
  buildtest/main.py
Labels: size/S

#1174 rename options for buildtest last log
  bash_completion.sh
  buildtest/cli/__init__.py
  buildtest/main.py
Labels: size/M

#1166 Add Spelling check CI
  .github/workflows/spellcheck.yml
  .spellcheck.yml
  .wordlist.txt
  docs/features.rst
Labels: size/M
