Repository buildtesters/buildtest, pull requests merged in 2022-09, with the labels that each got.

#1215 Add support for color themes with 'buildtest bc show' and 'buildtest bc show-fail'
  bash_completion.sh
  buildtest/cli/__init__.py
  buildtest/cli/buildspec.py
  buildtest/cli/help.py
  buildtest/main.py
  docs/gettingstarted/buildspecs_interface.rst
  tests/cli/test_buildspec.py
Labels: size/L

#1216 add color theme when viewing configuration file via 'buildtest config view --theme'
  bash_completion.sh
  buildtest/cli/__init__.py
  buildtest/cli/config.py
  tests/cli/test_config.py
Labels: size/M

#1218 add pagination for 'buildtest config view'
  bash_completion.sh
  buildtest/cli/__init__.py
  buildtest/cli/config.py
  tests/cli/test_config.py
Labels: size/S

#1217 refactor code reported by codacy
  buildtest/cli/buildspec.py
  buildtest/main.py
  buildtest/system.py
  buildtest/utils/tools.py
  tests/cli/test_buildspec.py
  tests/cli/test_inspect.py
  tests/cli/test_path.py
  tests/executors/test_base.py
  tests/utils/test_file.py
Labels: size/M

#1220 return non-zero returncode when using 'buildtest buildspec validate' with invalid buildspecs
  buildtest/cli/buildspec.py
  docs/gettingstarted/buildspecs_interface.rst
  tests/cli/test_buildspec.py
  tutorials/burstbuffer_datawarp_executors.yml
Labels: size/S

#1223 add 'set -e' when running Cori CI pipeline
  .gitlab/cori.yml
Labels: size/XS

#1207 Issue 1190 console color option
  bash_completion.sh
  buildtest/cli/__init__.py
  buildtest/cli/report.py
  docs/gettingstarted/query_test_report.rst
  tests/cli/test_report.py
Labels: size/L

#1228 update black version in .pre-commit-config.yaml
  .pre-commit-config.yaml
Labels: size/XS

#1229 update ascent gitlab CI/CD and remove github-gitlab mirroring workflow
  .github/workflows/mirror.yml
  .gitlab/ascent.yml
  .gitlab/cori.yml
  docs/contributing/github_integration.rst
Labels: size/M

#1230 remove buildtest timeline from documentation
  docs/what_is_buildtest.rst
Labels: size/S

#1232 update changelog
  CHANGELOG.rst
Labels: size/XS

#1233 add command aliases for several buildtest commands
  bash_completion.sh
  buildtest/cli/__init__.py
  buildtest/cli/config.py
  buildtest/cli/inspect.py
  buildtest/cli/report.py
  buildtest/main.py
Labels: size/L

#1234 Rename options for retrieving pass and failed test from report
  bash_completion.sh
  buildtest/cli/__init__.py
  buildtest/cli/help.py
  buildtest/cli/report.py
  docs/gettingstarted/query_test_report.rst
Labels: size/M

#1235 fail on warning during documentation builds
  .readthedocs.yaml
  docs/gettingstarted/query_test_report.rst
Labels: size/XS

#1236 update regression github workflow to stop after job step fails
  .github/workflows/installation.yml
  .github/workflows/regression.yml
  buildtest/cli/buildspec.py
  buildtest/cli/report.py
  tests/cli/test_buildspec.py
  tests/cli/test_report.py
Labels: size/S

#1237 rename option 'buildtest build --keep-stage-dir' to 'buildtest build --remove-stagedir'
  bash_completion.sh
  buildtest/cli/__init__.py
  buildtest/cli/build.py
  buildtest/main.py
  docs/gettingstarted/buildingtest.rst
  tests/cli/test_build.py
Labels: size/M

#1238 Added options --filterfields & formatfields
  bash_completion.sh
  buildtest/cli/__init__.py
  buildtest/cli/buildspec.py
  tests/cli/test_buildspec.py
Labels: size/M

#1243 use sphinx_designs to leverage dropdown feature in documentation
  buildtest/cli/report.py
  docs/conf.py
  docs/contributing/regression_testing.rst
  docs/features.rst
  docs/gettingstarted/buildingtest.rst
  docs/gettingstarted/buildspecs_interface.rst
  docs/gettingstarted/query_test_report.rst
  docs/installing_buildtest.rst
  docs/requirements.txt
  docs/schema_examples.rst
  docs/what_is_buildtest.rst
Labels: size/XXL

#1245 remove sphinx-tabs from documentation and replace with sphinx-design
  docs/buildspec_tutorial.rst
  docs/conf.py
  docs/installing_buildtest.rst
  docs/requirements.txt
Labels: size/M

#1242 Added bash completion for --filter & --format
  bash_completion.sh
Labels: size/S

#1246 Added --filterfields & --formatfields option
  bash_completion.sh
  buildtest/cli/__init__.py
  buildtest/cli/report.py
  docs/gettingstarted/query_test_report.rst
  tests/cli/test_report.py
Labels: size/M

#1248 add support for coloring output for buildspec cache
  bash_completion.sh
  buildtest/cli/__init__.py
  buildtest/cli/buildspec.py
  buildtest/cli/report.py
  buildtest/utils/tools.py
  tests/cli/test_buildspec.py
Labels: size/M

#1250 Add option to limit output of buildspec cache (buildtest buildspec find --count)
  bash_completion.sh
  buildtest/cli/__init__.py
  buildtest/cli/buildspec.py
  buildtest/cli/help.py
  docs/gettingstarted/buildspecs_interface.rst
Labels: size/M

#1251 Added tab completion for buildtest report --format & --filter
  bash_completion.sh
Labels: size/S
