Repository buildtesters/buildtest, pull requests merged in 2023-07, with the labels that each got.

#1510 minor improvements to Buildspec tutorial page
  docs/buildspec_tutorial.rst
  docs/buildspecs/buildspec_overview.rst
  docs/command_line_tutorial.rst
Labels: documentation, size/S

#1513 Issue 1508 fix error in config file for buildtest tutorials
  buildtest/settings/spack_container.yml
Labels: size/S

#1512 add python 3.11 in regression test remove 3.7
  .github/workflows/installation.yml
  .github/workflows/nightly_regression.yml
  .github/workflows/regression.yml
Labels: size/S

#1514 Bump python version dependency to 3.8
  .readthedocs.yaml
  bin/buildtest
  docs/installing_buildtest.rst
Labels: size/S

#1520 hardcode jsonschema version < 4.18 due to breaking feature in RefResolver
  requirements.txt
Labels: size/XS

#1522 fix issue with running buildtest with multiprocessing library
  bin/buildtest
Labels: size/XS

#1507 Add coverage to regex_check method
  .github/workflows/style.yml
  .gitignore
  docs/buildspecs/buildspec_overview.rst
  tests/builders/status_regex.yml
  tests/builders/test_builders.py
  tutorials/test_status/status_regex.yml
Labels: size/M

#1503 adding regression test for modules
  tests/cli/test_build.py
Labels: size/S

#1525 reorganize perlmutter tutorial and use todo directive
  docs/buildtest_perlmutter.rst
  docs/conf.py
  perlmutter_tutorial/ex1/.solution.txt
  perlmutter_tutorial/ex1/module_version.yml
  perlmutter_tutorial/ex2/.solution.sh
  perlmutter_tutorial/ex2/.solution.txt
  perlmutter_tutorial/ex3/.solution.sh
  perlmutter_tutorial/ex4/.solution.sh
  perlmutter_tutorial/ex4/.solution.txt
  perlmutter_tutorial/ex4/stream.yml
  perlmutter_tutorial/ex5/.solution.txt
  perlmutter_tutorial/ex5/hostname.yml
Labels: size/L

#1515 Add code coverage for multiple compilers with script schema
  tests/builders/stream_example.yml
  tests/builders/test_builders.py
  tutorials/test_status/status_regex.yml
Labels: size/M

#1537 update gitlab runners for nersc pipeline
  .gitlab/nersc.yml
Labels: size/XS

#1536 updating the github version workflow to 23.3.0
  .github/workflows/style.yml
Labels: size/XS

#1511 Add coverage to file_regex status check method
  tests/builders/regex_on_invalids.yml
  tests/builders/test_builders.py
Labels: size/M

#1531 add subsection 'Best Practices when creating Pull Request'
  docs/contributing/code_contribution_guide.rst
Labels: size/M

#1544 Several changes to documentation
  docs/command_line_tutorial.rst
  docs/contributing.rst
  docs/contributing/build_documentation.rst
  docs/contributing/code_contribution_guide.rst
  docs/gettingstarted/buildspecs_interface.rst
Labels: size/M

#1547 update to pyproject.toml with dependencies and use hatch build system
  buildtest/__init__.py
  pyproject.toml
  scripts/spack_container/doc-examples.py
  setup.csh
  setup.sh
Labels: size/M

#1548 update installation workflow by installing buildtest in zsh shell
  .github/workflows/installation.yml
Labels: size/M

#1541 Removed buildtest build option --disable-executor-check
  bash_completion.sh
  buildtest/cli/__init__.py
  buildtest/config.py
  buildtest/main.py
  buildtest/tools/tutorialexamples.py
  scripts/spack_container/doc-examples.py
  tests/builders/test_builders.py
  tests/executors/test_base.py
Labels: size/M

#1550 pin versions for documentation dependencies
  .readthedocs.yaml
  docs/requirements.txt
  pyproject.toml
Labels: size/M

#1538 Buildspec tutorial documentation fix
  buildtest/tools/docs.py
  docs/buildspecs/compiler.rst
  docs/buildspecs/spack.rst
  docs/buildtest_tutorial_examples/compilers/build/compiler_exclude.txt
  docs/buildtest_tutorial_examples/compilers/build/compiler_status_regex.txt
  docs/buildtest_tutorial_examples/compilers/build/custom_run.txt
  docs/buildtest_tutorial_examples/compilers/build/envvar_override.txt
  docs/buildtest_tutorial_examples/compilers/build/gnu_hello_c.txt
  docs/buildtest_tutorial_examples/compilers/build/gnu_hello_fortran.txt
  docs/buildtest_tutorial_examples/compilers/build/openmp_hello.txt
  docs/buildtest_tutorial_examples/compilers/build/pre_post_build_run.txt
  docs/buildtest_tutorial_examples/compilers/build/stream_example.txt
  docs/buildtest_tutorial_examples/compilers/build/stream_example_metrics.txt
  docs/buildtest_tutorial_examples/compilers/build/vecadd.txt
  docs/buildtest_tutorial_examples/compilers/inspect/compiler_status_regex.txt
  docs/buildtest_tutorial_examples/compilers/inspect/custom_run.txt
  docs/buildtest_tutorial_examples/compilers/inspect/envvar_override.txt
  docs/buildtest_tutorial_examples/compilers/inspect/gnu_hello_c.txt
  docs/buildtest_tutorial_examples/compilers/inspect/gnu_hello_fortran.txt
  docs/buildtest_tutorial_examples/compilers/inspect/openmp_hello.txt
  docs/buildtest_tutorial_examples/compilers/inspect/pre_post_build_run.txt
  docs/buildtest_tutorial_examples/compilers/inspect/stream_example.txt
  docs/buildtest_tutorial_examples/compilers/inspect/stream_openmp_metrics.txt
  docs/buildtest_tutorial_examples/spack/build/e4s_testsuite_mpich.txt
  docs/buildtest_tutorial_examples/spack/build/env_create_directory.txt
  docs/buildtest_tutorial_examples/spack/build/env_create_manifest.txt
  docs/buildtest_tutorial_examples/spack/build/env_install.txt
  docs/buildtest_tutorial_examples/spack/build/install_specs.txt
  docs/buildtest_tutorial_examples/spack/build/mirror_example.txt
  docs/buildtest_tutorial_examples/spack/build/pre_post_cmds.txt
  docs/buildtest_tutorial_examples/spack/build/remove_environment_example.txt
  docs/buildtest_tutorial_examples/spack/build/spack_sbatch.txt
  docs/buildtest_tutorial_examples/spack/build/spack_test.txt
  docs/buildtest_tutorial_examples/spack/build/spack_test_specs.txt
  docs/buildtest_tutorial_examples/spack/inspect/e4s_testsuite_mpich.txt
  docs/buildtest_tutorial_examples/spack/inspect/env_create_directory.txt
  docs/buildtest_tutorial_examples/spack/inspect/env_create_manifest.txt
  docs/buildtest_tutorial_examples/spack/inspect/env_install.txt
  docs/buildtest_tutorial_examples/spack/inspect/install_specs.txt
  docs/buildtest_tutorial_examples/spack/inspect/mirror_example.txt
  docs/buildtest_tutorial_examples/spack/inspect/pre_post_cmds.txt
  docs/buildtest_tutorial_examples/spack/inspect/remove_environment_example.txt
  docs/buildtest_tutorial_examples/spack/inspect/spack_sbatch.txt
  docs/buildtest_tutorial_examples/spack/inspect/spack_test.txt
  docs/buildtest_tutorial_examples/spack/inspect/spack_test_specs.txt
Labels: documentation, size/XXL

#1559 alias for buildtest config validate command
  bash_completion.sh
  buildtest/cli/__init__.py
  buildtest/cli/config.py
Labels: size/S

#1561 Refactor regression test for buildtest report and exclude coverage for some files
  buildtest/cli/report.py
  pyproject.toml
  tests/cli/test_report.py
Labels: size/L

#1563 fix behavior on running test when there is a failure
  buildtest/builders/base.py
  buildtest/executors/cobalt.py
  buildtest/executors/local.py
  buildtest/executors/lsf.py
  buildtest/executors/pbs.py
  buildtest/executors/slurm.py
  tests/settings/ascent.yml
  tests/settings/jlse.yml
  tests/settings/nersc.yml
  tests/settings/pbs.yml
Labels: size/L

#1564 Add Coverage to check runtime status
  tests/builders/runtime_status_test.yml
  tests/builders/test_builders.py
Labels: size/S

#1570 Fix spack clone example
  buildtest/tools/docs.py
  docs/buildspecs/spack.rst
  docs/buildtest_tutorial_examples/spack/build/clone_spack.txt
  docs/buildtest_tutorial_examples/spack/inspect/clone_spack.txt
  docs/contributing/build_documentation.rst
  docs/installing_buildtest.rst
  examples/spack/clone_spack.yml
  examples/spack/install_specs.yml
Labels: size/L

#1573 add PEARC23 slides
  docs/conferences.rst
Labels: size/XS

#1574 update Perlmutter tutorial
  docs/buildtest_perlmutter.rst
Labels: size/S

#1568 Modified behavior of --help/-h and added commands -H/--help--all
  bash_completion.sh
  buildtest/cli/__init__.py
Labels: new feature, size/M
