Repository buildtesters/buildtest, pull requests merged in 2023-06, with the labels that each got.

#1493 Create FUNDING.yml
  .github/FUNDING.yml
Labels: size/S

#1489 Add support for profiles
  README.rst
  bash_completion.sh
  buildtest/buildsystem/builders.py
  buildtest/cli/__init__.py
  buildtest/cli/build.py
  buildtest/cli/help.py
  buildtest/config.py
  buildtest/main.py
  buildtest/schemas/definitions.schema.json
  buildtest/schemas/settings.schema.json
  buildtest/settings/config.yml
  docs/configuring_buildtest/overview.rst
  docs/gettingstarted/buildingtest.rst
  tests/cli/test_build.py
Labels: size/L

#1498 reorganize compiler schema examples
  buildtest/schemas/examples/compiler.schema.json/invalid/additionalProperties/compiler.yml
  buildtest/schemas/examples/compiler.schema.json/invalid/additionalProperties/compiler_config.yml
  buildtest/schemas/examples/compiler.schema.json/invalid/additionalProperties/default_all.yml
  buildtest/schemas/examples/compiler.schema.json/invalid/additionalProperties/main.yml
  buildtest/schemas/examples/compiler.schema.json/invalid/examples.yml
  buildtest/schemas/examples/compiler.schema.json/invalid/missing_compilers.yml
  buildtest/schemas/examples/compiler.schema.json/invalid/missing_source.yml
  buildtest/schemas/examples/compiler.schema.json/invalid/module_load_duplicate.yml
  buildtest/schemas/examples/compiler.schema.json/invalid/module_load_min_items.yml
  buildtest/schemas/examples/compiler.schema.json/invalid/module_purge_type.yml
  buildtest/schemas/examples/compiler.schema.json/invalid/module_swap_duplicate.yml
  buildtest/schemas/examples/compiler.schema.json/invalid/module_swap_max_items.yml
  buildtest/schemas/examples/compiler.schema.json/invalid/module_swap_min_items.yml
  buildtest/schemas/examples/compiler.schema.json/invalid/module_type.yml
  buildtest/schemas/examples/compiler.schema.json/invalid/required_compiler.yml
  buildtest/schemas/examples/compiler.schema.json/invalid/uniqueitems_compiler_name.yml
  buildtest/schemas/examples/compiler.schema.json/valid/compiler_examples.yml
  buildtest/schemas/examples/compiler.schema.json/valid/environment.yml
  buildtest/schemas/examples/compiler.schema.json/valid/examples.yml
  buildtest/schemas/examples/compiler.schema.json/valid/jobsubmission_compiler_group.yml
  buildtest/schemas/examples/compiler.schema.json/valid/jobsubmission_for_all_compilers.yml
  buildtest/schemas/examples/compiler.schema.json/valid/mpi_launcher.yml
  buildtest/schemas/examples/compiler.schema.json/valid/multi_compilers.yml
  buildtest/schemas/examples/compiler.schema.json/valid/pre_post.yml
  buildtest/schemas/examples/compiler.schema.json/valid/run_args.yml
  buildtest/schemas/examples/compiler.schema.json/valid/status_returncode.yml
  buildtest/schemas/examples/compiler.schema.json/valid/variables.yml
  buildtest/schemas/examples/special_invalid_buildspecs/missing_type.yml
  tests/schema_tests/test_compiler.py
  tests/schema_tests/test_script.py
Labels: size/XXL

#1499 reorganize examples for spack.schema.json
  buildtest/schemas/examples/spack.schema.json/invalid/additionalProperties/spack.yml
  buildtest/schemas/examples/spack.schema.json/invalid/additionalProperties/spack_test.yml
  buildtest/schemas/examples/spack.schema.json/invalid/examples.yml
  buildtest/schemas/examples/spack.schema.json/invalid/mirror_type.yml
  buildtest/schemas/examples/spack.schema.json/invalid/spack_test_run_invalid_spec.yml
  buildtest/schemas/examples/spack.schema.json/invalid/specs_list_check_string.yml
  buildtest/schemas/examples/spack.schema.json/valid/env_activate.yml
  buildtest/schemas/examples/spack.schema.json/valid/env_concretize.yml
  buildtest/schemas/examples/spack.schema.json/valid/env_create_directory.yml
  buildtest/schemas/examples/spack.schema.json/valid/env_create_manifest.yml
  buildtest/schemas/examples/spack.schema.json/valid/env_create_name.yml
  buildtest/schemas/examples/spack.schema.json/valid/env_mirror.yml
  buildtest/schemas/examples/spack.schema.json/valid/examples.yml
  buildtest/schemas/examples/spack.schema.json/valid/install_without_env.yml
  buildtest/schemas/examples/spack.schema.json/valid/pre_post.yml
  buildtest/schemas/examples/spack.schema.json/valid/remove_spack_env_automatically.yml
  buildtest/schemas/examples/spack.schema.json/valid/remove_spack_environment.yml
  buildtest/schemas/examples/spack.schema.json/valid/sbatch_multi_executors.yml
  buildtest/schemas/examples/spack.schema.json/valid/sbatch_with_spack.yml
  buildtest/schemas/examples/spack.schema.json/valid/skip_test.yml
  buildtest/schemas/examples/spack.schema.json/valid/var_and_env_declaration.yml
  buildtest/schemas/examples/spack.schema.json/valid/vars_multi_executors.yml
  tests/schema_tests/test_script_compiler_and_spack.py
  tests/schema_tests/test_spack.py
Labels: size/XL

#1504 fix typo in git clone command
  docs/contributing/code_contribution_guide.rst
Labels: size/XS

#1501 Added coverage to --retry
  .gitignore
  buildtest/builders/base.py
  buildtest/cli/build.py
  buildtest/executors/local.py
  docs/contributing/github_integration.rst
  tests/cli/test_build.py
Labels: size/M
