Repository buildtesters/buildtest, pull requests merged in 2023-03, with the labels that each got.

#1406 create parent parser for --pager option used in subcommands
  bash_completion.sh
  buildtest/cli/__init__.py
  buildtest/cli/help.py
  docs/command_line_tutorial.rst
  tests/cli/test_buildspec.py
  tests/cli/test_config.py
  tests/cli/test_report.py
Labels: size/L

#1408 Add code coverage for subprocesses
  .coveragerc
  buildtest/tools/unittests.py
  setup.sh
  tests/sitecustomize.py
Labels: size/XS

#1407 increase test coverage
  bash_completion.sh
  buildtest/cli/info.py
  buildtest/cli/inspect.py
  tests/cli/test_build.py
  tests/cli/test_help.py
  tests/cli/test_inspect.py
Labels: size/L

#1410 update changelog
  CHANGELOG.rst
Labels: size/S

#1411 Fix symlink test failing on readthedocs container.
  tutorials/test_status/is_symlink.yml
Labels: size/XS

#1412 bump version of buildtest to 1.3
  buildtest/__init__.py
Labels: size/XS

#1413 add date for v1.3 release
  CHANGELOG.rst
Labels: size/XS

#1419 Build by multiple tags by providing tagnames as comma seperated list
  buildtest/cli/build.py
  buildtest/cli/help.py
  docs/gettingstarted/buildingtest.rst
  scripts/spack_container/doc-examples.py
  tests/cli/test_build.py
Labels: size/M

#1422 Metrics support with arbitrary file
  buildtest/builders/base.py
  buildtest/schemas/definitions.schema.json
  buildtest/schemas/examples/script.schema.json/invalid/examples.yml
  buildtest/schemas/examples/script.schema.json/valid/examples.yml
  docs/writing_buildspecs/performance_checks.rst
  tests/cli/test_build.py
  tutorials/metrics/invalid_metric_name.yml
  tutorials/metrics/invalid_metrics.yml
  tutorials/metrics/metrics_file_regex_invalid_file.yml
  tutorials/metrics/metrics_regex.yml
  tutorials/metrics/missing_required_in_metrics.yml
  tutorials/metrics_regex.yml
Labels: size/L

#1423 update hyperlink for badges in main docs page and README
  README.rst
  docs/index.rst
Labels: size/S

#1424 Add pagination support for buildtest history subcommands
  buildtest/cli/__init__.py
  buildtest/cli/help.py
  buildtest/cli/history.py
  tests/cli/test_history.py
Labels: size/M

#1428 Add pagination support for subcommands in "buildtest inspect" command
  bash_completion.sh
  buildtest/cli/__init__.py
  buildtest/cli/help.py
  buildtest/cli/inspect.py
  tests/cli/test_inspect.py
Labels: size/L

#1430 Rename github issue template for feature request.
  .github/ISSUE_TEMPLATE/cli_feature.yml
Labels: size/M
