Repository buildtesters/buildtest, pull requests merged in 2023-04, with the labels that each got.

#1431 Fix the bug report issue template
  .github/ISSUE_TEMPLATE/bug.yml
Labels: size/M

#1420 buildtest config compilers find --file
  bash_completion.sh
  buildtest/cli/__init__.py
  buildtest/cli/compilers.py
  tests/test_nersc.py
Labels: size/L

#1435 add buildtest talk at Improving Scientific Software 2023
  docs/conferences.rst
Labels: size/XS

#1436 remove codecov from pypi dependency
  .gitlab/ascent.yml
  .gitlab/nersc.yml
  docs/requirements.txt
Labels: size/XS

#1439 docs on assert less than
  docs/writing_buildspecs/performance_checks.rst
Labels: size/S

#1440 ensure executor names are alphanumeric
  buildtest/builders/base.py
  buildtest/cli/__init__.py
  buildtest/cli/inspect.py
  buildtest/schemas/examples/settings.schema.json/invalid/invalid_executor_names.yml
  buildtest/schemas/settings.schema.json
  tests/schema_tests/test_settings.py
Labels: size/M

#1441 fix date for conference talk at Improving Scientific Software Conference
  docs/conferences.rst
Labels: size/XS

#1442 remove CI/CD from Cori and refactor tests
  .gitlab/nersc.yml
  tests/examples/cori/burstbuffer.yml
  tests/examples/cori/exists.yml
  tests/examples/cori/hostname.yml
  tests/examples/perlmutter/hold_job.yml
  tests/examples/perlmutter/hostname.yml
  tests/settings/nersc.yml
  tests/test_nersc.py
Labels: size/L

#1451 autogenerate suite name for querying test results via spack test results
  buildtest/builders/spack.py
  buildtest/schemas/examples/spack.schema.json/invalid/examples.yml
  buildtest/schemas/examples/spack.schema.json/valid/examples.yml
  buildtest/schemas/spack.schema.json
  docs/buildspecs/spack.rst
  docs/buildtest_tutorial_examples/spack/build/spack_test.txt
  docs/buildtest_tutorial_examples/spack/inspect/spack_test.txt
  examples/spack/spack_test.yml
Labels: size/L

#1457 Rename buildspecs_roots in configuration file to 'root'
  buildtest/cli/buildspec.py
  buildtest/schemas/settings.schema.json
  buildtest/settings/config.yml
  docs/configuring_buildtest/overview.rst
Labels: size/M

#1458 Move purge settings to top-level in configuration file
  buildtest/cli/buildspec.py
  buildtest/schemas/settings.schema.json
  buildtest/settings/config.yml
  buildtest/settings/spack_container.yml
  tests/settings/ascent.yml
  tests/settings/jlse.yml
  tests/settings/nersc.yml
  tests/settings/pbs.yml
Labels: size/M
