Repository buildtesters/buildtest, pull requests merged in 2023-05, with the labels that each got.

#1459 add support for 'report' field in buildtest configuration to control behavior of 'buildtest report'
  buildtest/cli/buildspec.py
  buildtest/cli/cd.py
  buildtest/cli/inspect.py
  buildtest/cli/path.py
  buildtest/cli/report.py
  buildtest/cli/stats.py
  buildtest/main.py
  buildtest/schemas/examples/settings.schema.json/valid/cobalt-example.yml
  buildtest/schemas/examples/settings.schema.json/valid/combined_executor.yml
  buildtest/schemas/examples/settings.schema.json/valid/local-executor.yml
  buildtest/schemas/examples/settings.schema.json/valid/lsf-example.yml
  buildtest/schemas/examples/settings.schema.json/valid/pbs-example.yml
  buildtest/schemas/examples/settings.schema.json/valid/slurm-example.yml
  buildtest/schemas/settings.schema.json
  buildtest/settings/config.yml
  tests/cli/configuration/invalid_executors.yml
  tests/cli/test_buildspec.py
  tests/cli/test_compilers/invalid_moduletool.yml
  tests/cli/test_compilers/missing_compiler_find.yml
  tests/cli/test_inspect.py
  tests/cli/test_path.py
  tests/cli/test_report.py
  tests/test_stats.py
Labels: size/XL

#1460 documentation on configuring buildtest report section
  buildtest/settings/config.yml
  docs/configuring_buildtest/overview.rst
Labels: documentation, size/M

#1463 global option for --row-count
  bash_completion.sh
  buildtest/cli/__init__.py
  buildtest/cli/buildspec.py
  buildtest/cli/help.py
  buildtest/cli/history.py
  buildtest/cli/inspect.py
  buildtest/main.py
  tests/cli/test_buildspec.py
  tests/cli/test_history.py
  tests/cli/test_inspect.py
Labels: size/L

#1461 update changelog for 1.4 release
  CHANGELOG.rst
Labels: size/S

#1464 bump version to 1.4
  buildtest/__init__.py
Labels: size/XS

#1466 refactor codebase of 'buildtest inspect'
  buildtest/cli/inspect.py
  buildtest/main.py
  docs/buildspec_tutorial.rst
  tests/cli/test_inspect.py
Labels: size/L

#1467 add support to exclude tests by tagnames
  bash_completion.sh
  buildtest/buildsystem/builders.py
  buildtest/cli/__init__.py
  buildtest/cli/build.py
  buildtest/cli/help.py
  buildtest/main.py
  docs/gettingstarted/buildingtest.rst
Labels: size/L

#1468 show all records with --count when set to negative value
  buildtest/cli/__init__.py
  buildtest/cli/buildspec.py
  buildtest/cli/report.py
  docs/gettingstarted/query_test_report.rst
  tests/cli/test_buildspec.py
  tests/cli/test_report.py
Labels: size/L

#1469 move several options into parent parser
  buildtest/cli/__init__.py
  docs/buildspecs/spack.rst
  docs/command_line_tutorial.rst
  docs/facility_examples.rst
  docs/gettingstarted/query_test_report.rst
  docs/writing_buildspecs/multi_executor.rst
Labels: size/L

#1473 add a security page
  SECURITY.md
Labels: size/S

#1472 Increase Regression Test Coverage for BuildTest class
  buildtest/cli/build.py
  tests/cli/test_build.py
Labels: size/XL

#1474 Remove --list option from buildtest buildspec maintainers
  bash_completion.sh
  buildtest/cli/__init__.py
  buildtest/cli/buildspec.py
  buildtest/cli/help.py
  buildtest/main.py
  docs/gettingstarted/buildspecs_interface.rst
  tests/cli/test_buildspec.py
Labels: size/M

#1475 populate contributor names using ALL-CONTRIBUTORS bot
  .all-contributorsrc
  README.md
Labels: size/S

#1476 testing All contributors by updating README.md
  ALL-CONTRIBUTORS.md
Labels: size/XS

#1484 add link to video for ISS 2023
  docs/conferences.rst
Labels: size/XS

#1488 update precommit configuration file
  .pre-commit-config.yaml
Labels: size/XS
