Repository buildtesters/buildtest, pull requests merged in 2023-01, with the labels that each got.

#1326 add support for Assert Range
  buildtest/builders/base.py
  buildtest/schemas/definitions.schema.json
  buildtest/schemas/examples/script.schema.json/invalid/examples.yml
  buildtest/schemas/examples/script.schema.json/valid/examples.yml
  docs/buildspecs/performance_checks.rst
  tests/builders/assert_eq.yml
  tests/builders/assert_ge.yml
  tests/builders/assert_range.yml
  tests/builders/test_builders.py
  tutorials/perf_checks/assert_ge.yml
  tutorials/perf_checks/assert_range.yml
Labels: size/XL

#1329 Status Check based on file existence
  buildtest/builders/base.py
  buildtest/buildsystem/checks.py
  buildtest/buildsystem/parser.py
  buildtest/schemas/definitions.schema.json
  buildtest/schemas/examples/script.schema.json/invalid/examples.yml
  buildtest/schemas/examples/script.schema.json/valid/examples.yml
  buildtest/system.py
  docs/buildspecs/buildspec_overview.rst
  docs/buildspecs/performance_checks.rst
  tests/builders/exists.yml
  tests/builders/file_and_dir_check.yml
  tests/builders/test_builders.py
  tutorials/test_status/exists.yml
  tutorials/test_status/file_and_dir_check.yml
  tutorials/test_status/file_exists_exception.yml
  tutorials/test_status/file_exists_with_number.yml
Labels: size/L

#1331 fix bug with file check with slurm jobs
  buildtest/builders/base.py
  buildtest/buildsystem/checks.py
  tests/cli/test_config.py
  tests/examples/cori/exists.yml
  tests/test_cori.py
Labels: size/M

#1332 Move implementation of all status checks
  buildtest/builders/base.py
  buildtest/buildsystem/checks.py
Labels: size/XL

#1333 update changelog for version 1.1
  CHANGELOG.rst
Labels: size/M

#1334 buildtest version 1.1
  buildtest/__init__.py
Labels: size/XS

#1335 add a quick start guide and rearrange buildspec documentation
  docs/buildspec_tutorial.rst
  docs/buildtest_site.rst
  docs/conferences.rst
  docs/gettingstarted/buildingtest.rst
  docs/index.rst
  docs/installing_buildtest.rst
  docs/quick_start.rst
  docs/writing_buildspecs.rst
  docs/writing_buildspecs/customize_shell.rst
  docs/writing_buildspecs/global.rst
  docs/writing_buildspecs/multi_executor.rst
  docs/writing_buildspecs/test_dependency.rst
Labels: size/L

#1336 add documentation on troubleshooting buildtest
  docs/configuring_buildtest/overview.rst
  docs/features.rst
  docs/index.rst
  docs/troubleshooting.rst
Labels: documentation, size/M

#1340 update logic for printing exception messages for invalid buildspecs
  buildtest/cli/buildspec.py
  buildtest/exceptions.py
Labels: size/M

#1339 Assert less than and equal status check
  buildtest/builders/base.py
  buildtest/buildsystem/checks.py
  buildtest/schemas/definitions.schema.json
  docs/buildspecs/performance_checks.rst
  tests/builders/assert_le.yml
  tests/builders/test_builders.py
  tutorials/perf_checks/assert_le.yml
Labels: size/L

#1344 remove broken slack badge link
  README.rst
  docs/index.rst
  docs/what_is_buildtest.rst
Labels: size/S

#1345 rewrite page Building and Test Process
  docs/_static/GeneralPipeline.png
  docs/_static/ParserDiagram.png
  docs/builder.rst
Labels: size/L

#1350 change executor match from equality check to regex (re.fullmatch)
  buildtest/buildsystem/parser.py
Labels: size/XS

#1338 buildtest tutorial on perlmutter
  docs/builder.rst
  docs/buildspecs/performance_checks.rst
  docs/buildtest_perlmutter.rst
  docs/index.rst
  docs/writing_buildspecs/global.rst
  perlmutter_tutorial/ex1/.solution.txt
  perlmutter_tutorial/ex1/hostname.yml
  perlmutter_tutorial/ex2/.solution.txt
  perlmutter_tutorial/ex2/module_version.yml
  perlmutter_tutorial/ex3/.solution.txt
  perlmutter_tutorial/ex4/.solution.txt
  perlmutter_tutorial/ex5/.solution.txt
  perlmutter_tutorial/ex5/stream.yml
Labels: documentation, size/L

#1352 fix format issue in codeblock
  docs/builder.rst
Labels: documentation

#1351 relocate pages for buildtest tutorial in 'References'
  docs/getting_started.rst
  docs/gettingstarted/buildingtest.rst
  docs/gettingstarted/query_test_report.rst
  docs/index.rst
Labels: size/S

#1354 Assert greater than status check
  buildtest/builders/base.py
  buildtest/buildsystem/checks.py
  buildtest/schemas/definitions.schema.json
  tests/builders/assert_gt.yml
  tests/builders/test_builders.py
  tutorials/perf_checks/assert_gt.yml
Labels: size/L

#1356 run regression test on file changes
  .github/workflows/regression.yml
  buildtest/__init__.py
Labels: size/XS

#1359 run CI job with bdtest
  .gitlab/cori.yml
Labels: size/S

#1353 buildtest command line tutorial
  docs/buildspecs/buildspec_overview.rst
  docs/command_line_tutorial.rst
  docs/gettingstarted/buildingtest.rst
  docs/index.rst
Labels: documentation, size/L

#1360 Run ci on perlmutter and add method to run on perlmutter
  .gitlab/nersc.yml
  tests/settings/nersc.yml
  tests/test_nersc.py
Labels: size/M
