Repository buildtesters/buildtest, pull requests merged in 2023-08, with the labels that each got.

#1567 Add --detailed option for buildtest report
  bash_completion.sh
  buildtest/cli/__init__.py
  buildtest/cli/report.py
  docs/gettingstarted/query_test_report.rst
  pyproject.toml
  tests/cli/test_report.py
Labels: size/M

#1578 remove 'buildtest help' and 'buildtest h' from tab completion
  bash_completion.sh
Labels: size/XS

#1540 Add buildtest commands option
  bash_completion.sh
  buildtest/cli/__init__.py
  buildtest/cli/commands.py
  buildtest/main.py
  tests/cli/test_commands.py
Labels: size/M

#1580 fix where buildtest commands were printed in every run
  buildtest/cli/commands.py
Labels: size/M

#1543 add changelog for v1.5
  CHANGELOG.rst
Labels: size/M

#1582 increment buildtest version to 1.5
  buildtest/__init__.py
Labels: size/XS

#1552 listing all buildtest config profiles list
  bash_completion.sh
  buildtest/cli/__init__.py
  buildtest/cli/config.py
  buildtest/cli/show.py
  buildtest/settings/config.yml
  docs/configuring_buildtest/overview.rst
  tests/cli/test_config.py
Labels: size/L

#1586 change message for 'buildtest config profiles list' when no profiles are found
  buildtest/cli/config.py
Labels: size/XS

#1588 Move compiler listing to command 'buildtest config compilers list'
  bash_completion.sh
  buildtest/cli/__init__.py
  buildtest/cli/compilers.py
  buildtest/cli/show.py
  docs/configuring_buildtest/compilers.rst
Labels: size/M

#1587 Added support to deactivate spack environments
  buildtest/builders/spack.py
  buildtest/schemas/examples/spack.schema.json/invalid/spack_env_deactivate.yml
  buildtest/schemas/examples/spack.schema.json/valid/spack_env_deactivate.yml
  buildtest/schemas/spack.schema.json
  buildtest/tools/docs.py
  docs/buildspecs/spack.rst
  docs/buildtest_tutorial_examples/spack/build/spack_env_deactivate.txt
  docs/buildtest_tutorial_examples/spack/inspect/spack_env_deactivate.txt
  examples/spack/spack_env_deactivate.yml
Labels: size/L

#1595 default maxpendtime set for 1 day
  buildtest/executors/base.py
  buildtest/executors/cobalt.py
  buildtest/executors/lsf.py
  buildtest/executors/pbs.py
Labels: size/XS

#1592 remove compilers from buildtest configuration file
  bash_completion.sh
  buildtest/cli/__init__.py
  buildtest/cli/compilers.py
  buildtest/cli/show.py
  docs/configuring_buildtest/compilers.rst
  tests/test_nersc.py
Labels: size/L

#1596 move pytest configuration to pyproject.toml
  pyproject.toml
  pytest.ini
Labels: size/S

#1597 remove ALL-CONTRIBUTORS.md
  ALL-CONTRIBUTORS.md
Labels: size/S

#1598 removing .all-contributorsrc file
  .all-contributorsrc
Labels: size/M

#1599 Add short option -t for --testpath
  buildtest/cli/__init__.py
  buildtest/tools/docs.py
  docs/buildspecs/compiler.rst
  docs/buildspecs/spack.rst
  docs/buildtest_tutorial_examples/compilers/inspect/custom_run.txt
  docs/buildtest_tutorial_examples/compilers/inspect/envvar_override.txt
  docs/buildtest_tutorial_examples/compilers/inspect/gnu_hello_c.txt
  docs/buildtest_tutorial_examples/compilers/inspect/gnu_hello_fortran.txt
  docs/buildtest_tutorial_examples/compilers/inspect/openmp_hello.txt
  docs/buildtest_tutorial_examples/compilers/inspect/pre_post_build_run.txt
  docs/buildtest_tutorial_examples/compilers/inspect/stream_example.txt
  docs/buildtest_tutorial_examples/spack/inspect/clone_spack.txt
  docs/buildtest_tutorial_examples/spack/inspect/e4s_testsuite_mpich.txt
  docs/buildtest_tutorial_examples/spack/inspect/env_create_directory.txt
  docs/buildtest_tutorial_examples/spack/inspect/env_create_manifest.txt
  docs/buildtest_tutorial_examples/spack/inspect/env_install.txt
  docs/buildtest_tutorial_examples/spack/inspect/install_specs.txt
  docs/buildtest_tutorial_examples/spack/inspect/mirror_example.txt
  docs/buildtest_tutorial_examples/spack/inspect/pre_post_cmds.txt
  docs/buildtest_tutorial_examples/spack/inspect/remove_environment_example.txt
  docs/buildtest_tutorial_examples/spack/inspect/spack_sbatch.txt
  docs/buildtest_tutorial_examples/spack/inspect/spack_test.txt
  docs/buildtest_tutorial_examples/spack/inspect/spack_test_specs.txt
  docs/command_line_tutorial.rst
  docs/facility_examples.rst
  docs/gettingstarted/query_test_report.rst
  docs/writing_buildspecs/multi_executor.rst
Labels: size/L

#1585 removing profiles automatically via buildtest config profiles remove
  bash_completion.sh
  buildtest/cli/__init__.py
  buildtest/cli/config.py
  buildtest/cli/show.py
  buildtest/settings/config.yml
  docs/configuring_buildtest/overview.rst
  tests/cli/test_config.py
Labels: size/L

#1601 buildtest regression test run in unique directory for every CI run
  buildtest/defaults.py
  buildtest/tools/unittests.py
Labels: size/S

#1602 add open_collective link in funding.yml
  .github/FUNDING.yml
Labels: size/XS

#1603 Use unique directory when performing documentation build
  buildtest/cli/show.py
  buildtest/defaults.py
  buildtest/tools/unittests.py
  docs/conf.py
  docs/contributing/regression_testing.rst
  docs/gettingstarted/buildingtest.rst
Labels: size/S

#1604 exclude cdash url from url check
  .github/workflows/urlchecker.yml
Labels: size/XS

#1605 make use of tempfile when writing stdout content for 'buildtest build'
  buildtest/main.py
Labels: size/S

#1608 readthedocs build to not fail on warning messages
  .readthedocs.yaml
Labels: size/XS

#1606 upgrade dependencies for docutils, sphinx, sphinx-rtd-theme, sphinx-design
  docs/requirements.txt
  pyproject.toml
Labels: size/S

#1611 Rewrite bash completion script by using case statements
  bash_completion.sh
Labels: size/L
