Repository buildtesters/buildtest, pull requests merged in 2023-02, with the labels that each got.

#1357 update to perlmutter tutorial page
  docs/builder.rst
  docs/buildtest_perlmutter.rst
  docs/features.rst
Labels: size/L

#1362 update year in license file
  LICENSE
Labels: size/XS

#1361 Assert not equal status check
  buildtest/builders/base.py
  buildtest/buildsystem/checks.py
  buildtest/schemas/definitions.schema.json
  docs/configuring_buildtest/compilers.rst
  tests/builders/assert_gt.yml
  tests/builders/assert_le.yml
  tests/builders/assert_ne.yml
  tests/builders/test_builders.py
  tutorials/perf_checks/assert_ne.yml
Labels: size/L

#1364 add support for 'contains' and 'not contains' status check
  buildtest/builders/base.py
  buildtest/buildsystem/checks.py
  buildtest/schemas/definitions.schema.json
  tests/builders/contains.yml
  tests/builders/test_builders.py
  tutorials/perf_checks/contains.yml
Labels: size/L

#1365 rewrite performance checks page
  docs/buildspec_tutorial.rst
  docs/contributing.rst
  docs/contributing/github_integration.rst
  docs/what_is_buildtest.rst
  docs/writing_buildspecs.rst
  docs/writing_buildspecs/performance_checks.rst
Labels: size/L

#1367 Move perlmutter podman instructions to podman tab
  docs/buildspec_tutorial.rst
Labels: size/M

#1371 add talk on Automated Acceptance Testing in HPC with buildtest
  docs/conferences.rst
Labels: size/XS

#1368 Add e4s_testsuite tutorial section
  buildtest/tools/docs.py
  docs/buildspec_tutorial.rst
  docs/buildspecs/e4s_testsuite.rst
  docs/buildtest_tutorial_examples/spack/build/e4s_testsuite_mpich.txt
  docs/buildtest_tutorial_examples/spack/inspect/e4s_testsuite_mpich.txt
  examples/spack/e4s_testsuite_mpich.yml
Labels: size/L

#1372 Autogenerate tutorial examples
  docs/buildtest_tutorial_examples/compilers/build/compiler_exclude.txt
  docs/buildtest_tutorial_examples/compilers/build/compiler_status_regex.txt
  docs/buildtest_tutorial_examples/compilers/build/custom_run.txt
  docs/buildtest_tutorial_examples/compilers/build/envvar_override.txt
  docs/buildtest_tutorial_examples/compilers/build/gnu_hello_c.txt
  docs/buildtest_tutorial_examples/compilers/build/gnu_hello_fortran.txt
  docs/buildtest_tutorial_examples/compilers/build/openmp_hello.txt
  docs/buildtest_tutorial_examples/compilers/build/pre_post_build_run.txt
  docs/buildtest_tutorial_examples/compilers/build/stream_example.txt
  docs/buildtest_tutorial_examples/compilers/build/stream_example_metrics.txt
  docs/buildtest_tutorial_examples/compilers/build/vecadd.txt
  docs/buildtest_tutorial_examples/compilers/inspect/compiler_status_regex.txt
  docs/buildtest_tutorial_examples/compilers/inspect/custom_run.txt
  docs/buildtest_tutorial_examples/compilers/inspect/envvar_override.txt
  docs/buildtest_tutorial_examples/compilers/inspect/gnu_hello_c.txt
  docs/buildtest_tutorial_examples/compilers/inspect/gnu_hello_fortran.txt
  docs/buildtest_tutorial_examples/compilers/inspect/openmp_hello.txt
  docs/buildtest_tutorial_examples/compilers/inspect/pre_post_build_run.txt
  docs/buildtest_tutorial_examples/compilers/inspect/stream_example.txt
  docs/buildtest_tutorial_examples/compilers/inspect/stream_openmp_metrics.txt
  docs/buildtest_tutorial_examples/spack/build/e4s_testsuite_mpich.txt
  docs/buildtest_tutorial_examples/spack/build/env_create_directory.txt
  docs/buildtest_tutorial_examples/spack/build/env_create_manifest.txt
  docs/buildtest_tutorial_examples/spack/build/env_install.txt
  docs/buildtest_tutorial_examples/spack/build/install_specs.txt
  docs/buildtest_tutorial_examples/spack/build/mirror_example.txt
  docs/buildtest_tutorial_examples/spack/build/pre_post_cmds.txt
  docs/buildtest_tutorial_examples/spack/build/remove_environment_example.txt
  docs/buildtest_tutorial_examples/spack/build/spack_sbatch.txt
  docs/buildtest_tutorial_examples/spack/build/spack_test.txt
  docs/buildtest_tutorial_examples/spack/build/spack_test_specs.txt
  docs/buildtest_tutorial_examples/spack/inspect/e4s_testsuite_mpich.txt
  docs/buildtest_tutorial_examples/spack/inspect/env_create_directory.txt
  docs/buildtest_tutorial_examples/spack/inspect/env_create_manifest.txt
  docs/buildtest_tutorial_examples/spack/inspect/env_install.txt
  docs/buildtest_tutorial_examples/spack/inspect/install_specs.txt
  docs/buildtest_tutorial_examples/spack/inspect/mirror_example.txt
  docs/buildtest_tutorial_examples/spack/inspect/pre_post_cmds.txt
  docs/buildtest_tutorial_examples/spack/inspect/remove_environment_example.txt
  docs/buildtest_tutorial_examples/spack/inspect/spack_sbatch.txt
  docs/buildtest_tutorial_examples/spack/inspect/spack_test.txt
  docs/buildtest_tutorial_examples/spack/inspect/spack_test_specs.txt
  examples/compilers/stream_example_metrics.yml
Labels: size/XXL

#1363 update changelog for v1.2 release
  CHANGELOG.rst
Labels: size/S

#1373 bump release to 1.2
  buildtest/__init__.py
Labels: size/XS

#1376 fix issue in documentation on spack page
  docs/buildspecs/spack.rst
Labels: size/XS

#1379 rename solution files for ex3 and ex4 into shell scripts and fix error in solution
  perlmutter_tutorial/ex3/.solution.sh
  perlmutter_tutorial/ex3/.solution.txt
  perlmutter_tutorial/ex4/.solution.sh
  perlmutter_tutorial/ex4/.solution.txt
Labels: size/M

#1377 Add feature buildtest buildspec find --row-count
  bash_completion.sh
  buildtest/cli/__init__.py
  buildtest/cli/buildspec.py
  buildtest/cli/help.py
  docs/gettingstarted/buildspecs_interface.rst
  tests/cli/test_buildspec.py
Labels: size/M

#1382 Assert Less Than for Status Check
  buildtest/builders/base.py
  buildtest/buildsystem/checks.py
  buildtest/schemas/definitions.schema.json
  tests/builders/assert_lt.yml
  tests/builders/test_builders.py
  tutorials/perf_checks/assert_lt.yml
Labels: size/L

#1378 Added trigger for nightly regression test on master
  .github/workflows/regression.yml
Labels: size/XS

#1383 add option 'buildtest inspect query --theme' to select color theme
  bash_completion.sh
  buildtest/cli/__init__.py
  buildtest/cli/inspect.py
  tests/cli/test_inspect.py
Labels: size/S

#1386 add link to video for ECP Tutorial 2023
  docs/conferences.rst
Labels: size/XS

#1385 add yamllinter and shell linter check
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/cli_feature.yml
  .github/ISSUE_TEMPLATE/documentation.yml
  .github/dependabot.yml
  .github/workflows/build_container.yml
  .github/workflows/installation.yml
  .github/workflows/jsonschemadocs.yml
  .github/workflows/shellcheck.yml
  .github/workflows/style.yml
  .gitlab/ascent.yml
  .gitlab/nersc.yml
  .pre-commit-config.yaml
  .shellcheckrc
  .yamllint.yml
  README.rst
  bin/buildtest
  buildtest/schemas/examples/compiler.schema.json/invalid/examples.yml
  buildtest/schemas/examples/compiler.schema.json/valid/examples.yml
  buildtest/schemas/examples/global.schema.json/invalid/exceed_testname_length.yml
  buildtest/schemas/examples/global.schema.json/invalid/invalid_pattern.yml
  buildtest/schemas/examples/global.schema.json/invalid/maintainers_type_mismatch.yml
  buildtest/schemas/examples/global.schema.json/invalid/unique_maintainers.yml
  buildtest/schemas/examples/global.schema.json/valid/examples.yml
  buildtest/schemas/examples/script.schema.json/valid/examples.yml
  buildtest/schemas/examples/settings.schema.json/valid/cobalt-example.yml
  buildtest/schemas/examples/settings.schema.json/valid/combined_executor.yml
  buildtest/schemas/examples/settings.schema.json/valid/lsf-example.yml
  buildtest/schemas/examples/settings.schema.json/valid/pbs-example.yml
  buildtest/schemas/examples/settings.schema.json/valid/slurm-example.yml
  buildtest/schemas/examples/spack.schema.json/invalid/examples.yml
  buildtest/schemas/examples/spack.schema.json/valid/examples.yml
  docs/requirements.txt
  scripts/spack_container/install.sh
  scripts/spack_container/regtest-tutorial.sh
  scripts/spack_container/setup.sh
  scripts/spack_container/spack_setup.sh
  setup.csh
  setup.sh
Labels: size/L

#1389 Added precommit ci for auto-updating precommit config
  .pre-commit-config.yaml
Labels: size/XS

#1390 add contribution section on yamllint and shellcheck
  docs/contributing/code_contribution_guide.rst
Labels: size/M

#1391 update onboarding checklist and add new section on offboarding
  docs/contributing/new_maintainer_checklist.rst
Labels: size/M

#1393 document BUILDTEST_FFLAGS environment variable
  docs/buildspecs/compiler.rst
Labels: size/XS

#1392 add support for global pager option
  bash_completion.sh
  buildtest/cli/__init__.py
  buildtest/cli/help.py
  docs/command_line_tutorial.rst
  tests/cli/test_buildspec.py
  tests/cli/test_config.py
  tests/cli/test_report.py
Labels: size/L

#1394 Add status check for Symlink check
  .github/workflows/regression.yml
  buildtest/builders/base.py
  buildtest/buildsystem/checks.py
  buildtest/schemas/definitions.schema.json
  buildtest/schemas/examples/script.schema.json/invalid/examples.yml
  buildtest/schemas/examples/script.schema.json/valid/examples.yml
  buildtest/utils/file.py
  docs/buildspecs/buildspec_overview.rst
  tests/builders/is_symlink.yml
  tests/builders/test_builders.py
  tests/buildsystem/invalid_builds/invalid_file.yml
  tests/examples/cori/hostname.yml
  tests/settings/pbs.yml
  tests/utils/test_file.py
  tutorials/test_status/is_symlink.yml
Labels: size/L

#1396 regex on arbitrary file names via 'file_regex'
  buildtest/builders/base.py
  buildtest/buildsystem/checks.py
  buildtest/schemas/definitions.schema.json
  buildtest/schemas/examples/script.schema.json/invalid/examples.yml
  buildtest/schemas/examples/script.schema.json/valid/examples.yml
  docs/__init__.py
  docs/buildspecs/buildspec_overview.rst
  tests/builders/regex_on_filename.yml
  tutorials/test_status/regex_on_filename.yml
Labels: size/L

#1400 update hyperlink for documentation badge
  README.rst
  docs/index.rst
Labels: size/XS

#1399 disable PDF format for docs
  .readthedocs.yaml
Labels: size/XS

#1401 update link for docs badge to use 'devel' branch
  README.rst
  docs/index.rst
Labels: size/XS

#1404 Fix all yamllint errors
  tests/buildsystem/invalid_builds/invalid_file.yml
  tests/buildsystem/invalid_builds/invalid_lang_ext.yml
  tests/buildsystem/invalid_buildspecs/invalid_executor.yml
  tests/buildsystem/invalid_buildspecs/invalid_type.yml
  tests/buildsystem/invalid_buildspecs/missing_executor.yml
  tests/buildsystem/invalid_buildspecs/missing_type.yml
  tests/buildsystem/valid_builds/sched_directives.yml
  tests/buildsystem/valid_buildspecs/gnu_hello_c.yml
  tests/buildsystem/valid_buildspecs/pre_post_build_run.yml
  tests/buildsystem/valid_buildspecs/shell_examples.yml
  tests/cli/cdash_examples/invalid_project.yml
  tests/cli/cdash_examples/invalid_url.yml
  tests/cli/configuration/invalid_executors.yml
  tests/cli/test_compilers/invalid_moduletool.yml
  tests/cli/test_compilers/missing_compiler_find.yml
  tests/examples/ascent/lsf_job_state.yml
  tests/examples/cori/exists.yml
  tests/examples/cori/hostname.yml
  tests/examples/jlse/hold_job.yml
  tests/examples/jlse/hostname.yml
  tests/examples/pbs/hold.yml
  tests/examples/pbs/job_dependency.yml
  tests/examples/pbs/multiple_tests.yml
  tests/settings/nersc.yml
  tutorials/perf_checks/assert_eq.yml
  tutorials/perf_checks/assert_ge.yml
  tutorials/perf_checks/assert_gt.yml
  tutorials/perf_checks/assert_le.yml
  tutorials/perf_checks/assert_lt.yml
  tutorials/perf_checks/assert_ne.yml
  tutorials/perf_checks/assert_range.yml
  tutorials/perf_checks/contains.yml
  tutorials/test_status/exists.yml
  tutorials/test_status/file_and_dir_check.yml
  tutorials/test_status/is_symlink.yml
Labels: size/L
