Repository buildtesters/buildtest, pull requests merged in 2024-03, with the labels that each got.

#1721 update codecov to disable patch and annotations
  .codecov.yml
Labels: size/XS

#1722 add linecount status check for comparing stdout/stderr with expected number of lines
  buildtest/builders/base.py
  buildtest/buildsystem/checks.py
  buildtest/schemas/definitions.schema.json
  buildtest/schemas/examples/script.schema.json/invalid/linecount_stream_mismatch.yml
  buildtest/schemas/examples/script.schema.json/valid/linecount.yml
  docs/writing_buildspecs.rst
  docs/writing_buildspecs/status_check.rst
  tests/builders/linecount.yml
  tests/builders/test_builders.py
  tutorials/test_status/linecount.yml
Labels: size/L

#1723 add support for file line count status check
  buildtest/builders/base.py
  buildtest/buildsystem/checks.py
  buildtest/schemas/definitions.schema.json
  buildtest/schemas/examples/script.schema.json/invalid/file_linecount_invalid.yml
  buildtest/schemas/examples/script.schema.json/valid/file_linecount.yml
  docs/writing_buildspecs/status_check.rst
  tests/builders/file_linecount.yml
  tests/builders/file_linecount_failure.yml
  tests/builders/file_linecount_invalid.yml
  tests/builders/test_builders.py
  tests/cli/test_buildspec.py
  tests/schema_tests/test_schemas.py
  tutorials/test_status/file_linecount.yml
  tutorials/test_status/file_linecount_failure.yml
  tutorials/test_status/file_linecount_invalid.yml
  tutorials/test_status/linecount.yml
Labels: size/L

#1724 fix bug in save-profile not working
  buildtest/cli/build.py
Labels: size/XS

#1728 enable fail_on_warning in .readthedocs.yaml
  .readthedocs.yaml
  buildtest/defaults.py
Labels: size/S

#1729 add --validate option for buildtest build
  bash_completion.sh
  buildtest/cli/__init__.py
  buildtest/cli/build.py
  buildtest/cli/show.py
  buildtest/main.py
  buildtest/schemas/settings.schema.json
  docs/batch_support.rst
  docs/gettingstarted/buildingtest.rst
  docs/scripting_examples/ex1.py
  docs/troubleshooting.rst
  tests/buildsystem/test_spack.py
  tests/cli/test_build.py
Labels: size/M

#1730 add support for regular expression types (re.search, re.match, re.fullmatch) in status check and metrics definition
  buildtest/builders/base.py
  buildtest/buildsystem/checks.py
  buildtest/schemas/definitions.schema.json
  buildtest/schemas/examples/script.schema.json/invalid/invalid_re_value.yml
  buildtest/schemas/examples/script.schema.json/valid/metrics_with_regex_type.yml
  buildtest/schemas/examples/script.schema.json/valid/specify_regex_type.yml
  docs/writing_buildspecs/performance_checks.rst
  docs/writing_buildspecs/status_check.rst
  tests/builders/metrics_with_regex_type.yml
  tests/builders/specify_regex_type.yml
  tests/builders/test_builders.py
  tutorials/metrics/metrics_with_regex_type.yml
  tutorials/test_status/specify_regex_type.yml
Labels: size/L

#1733 rearrange documentation page for Test Status and Metrics
  docs/builder.rst
  docs/buildspecs/aws.rst
  docs/buildspecs/buildspec_overview.rst
  docs/buildtest_perlmutter.rst
  docs/writing_buildspecs.rst
  docs/writing_buildspecs/comparison_operators.rst
  docs/writing_buildspecs/metrics.rst
  docs/writing_buildspecs/status_check.rst
Labels: size/XXL

#1734 Add support for torque scheduler
  aws_oddc/sleep.yml
  buildtest/builders/base.py
  buildtest/config.py
  buildtest/exceptions.py
  buildtest/executors/pbs.py
  buildtest/executors/setup.py
  buildtest/scheduler/pbs.py
  buildtest/schemas/settings.schema.json
  buildtest/settings/aws_oddc_pbs.yml
  buildtest/system.py
  pyproject.toml
  tests/settings/pbs.yml
Labels: size/L

#1738 improve scheduler detection logic and add torque queue detection when validating executors
  buildtest/scheduler/detection.py
  buildtest/scheduler/pbs.py
  buildtest/system.py
Labels: size/XL

#1735 Extract line number in metrics declaration
  buildtest/builders/base.py
  buildtest/schemas/definitions.schema.json
  tests/builders/metrics_regex_with_invalid_linenum.yml
  tests/builders/metrics_regex_with_linenum.yml
  tests/builders/test_builders.py
  tutorials/metrics/metrics_regex_with_invalid_linenum.yml
  tutorials/metrics/metrics_regex_with_linenum.yml
Labels: size/L
