Repository buildtesters/buildtest, pull requests merged in 2024-04, with the labels that each got.

#1739 Enhancement to scheduler logic and code refactoring.
  buildtest/executors/base.py
  buildtest/executors/cobalt.py
  buildtest/executors/slurm.py
  buildtest/scheduler/cobalt.py
  buildtest/scheduler/job.py
  buildtest/scheduler/lsf.py
  buildtest/scheduler/pbs.py
  buildtest/scheduler/slurm.py
  tests/examples/jlse/hold_job.yml
  tests/examples/jlse/hostname.yml
  tests/settings/jlse.yml
Labels: size/L

#1741 Add documentation for Torque Executors
  docs/batch_support.rst
  docs/configuring_buildtest/executors.rst
Labels: documentation, size/XL

#1742 Improvement to Scheduler Detection and improve logging for executor validation
  buildtest/config.py
  buildtest/scheduler/detection.py
Labels: size/L

#1746 Change Poll commands for PBS and Torque and add support for retrieving job data
  buildtest/buildsystem/builders.py
  buildtest/scheduler/pbs.py
  tests/test_pbs.py
Labels: size/M

#1747 Refactor code BuildTest class
  buildtest/buildsystem/builders.py
  buildtest/cli/build.py
  buildtest/main.py
  buildtest/schemas/examples/settings.schema.json/valid/combined_executor.yml
  tests/builders/test_builders.py
  tests/builders/test_containers.py
  tests/buildsystem/test_base.py
  tests/buildsystem/test_spack.py
  tests/cli/test_build.py
  tests/cli/test_cdash.py
  tests/cli/test_config.py
  tests/cli/test_history.py
  tests/examples/torque/sleep.yml
  tests/examples/torque/sleep_cancel.yml
  tests/executors/test_base.py
  tests/test_ascent.py
  tests/test_jlse.py
  tests/test_nersc.py
  tests/test_pbs.py
  tests/test_stats.py
  tests/test_torque.py
Labels: size/L

#1748 Improvements to LSF executors and rewrite regression test
  buildtest/config.py
  buildtest/executors/base.py
  buildtest/scheduler/lsf.py
  buildtest/system.py
  docs/batch_support.rst
  docs/configuring_buildtest/site_examples.rst
  tests/examples/summit/hold_job.yml
  tests/examples/summit/hostname.yml
  tests/examples/summit/lsf_job_state.yml
  tests/settings/summit.yml
  tests/test_summit.py
Labels: size/XL

#1750 Refactor code for LSF queue validation for executor check
  buildtest/config.py
  buildtest/scheduler/detection.py
  docs/batch_support.rst
  docs/configuring_buildtest/site_examples.rst
  tests/settings/summit.yml
Labels: size/M

#1736 update changelog for v2.0
  CHANGELOG.rst
Labels: size/M

#1755 bump version to 2.0
  buildtest/__init__.py
Labels: size/XS

#1757 Add support for 'paths' in configuration to allow one to search for scheduler binary in non-standard location
  aws_oddc/sleep.yml
  buildtest/config.py
  buildtest/executors/base.py
  buildtest/executors/cobalt.py
  buildtest/executors/lsf.py
  buildtest/executors/pbs.py
  buildtest/executors/setup.py
  buildtest/executors/slurm.py
  buildtest/scheduler/cobalt.py
  buildtest/scheduler/detection.py
  buildtest/scheduler/lsf.py
  buildtest/scheduler/pbs.py
  buildtest/scheduler/slurm.py
  buildtest/schemas/examples/settings.schema.json/valid/cobalt-example.yml
  buildtest/schemas/examples/settings.schema.json/valid/combined_executor.yml
  buildtest/schemas/examples/settings.schema.json/valid/lsf-example.yml
  buildtest/schemas/examples/settings.schema.json/valid/pbs-example.yml
  buildtest/schemas/examples/settings.schema.json/valid/slurm-example.yml
  buildtest/schemas/examples/settings.schema.json/valid/torque-example.yml
  buildtest/schemas/settings.schema.json
  buildtest/settings/aws_oddc_pbs.yml
  buildtest/settings/config.yml
  buildtest/system.py
  buildtest/utils/tools.py
  docs/configuring_buildtest/overview.rst
  scripts/pbs/setup.sh
  tests/examples/pbs/job_dependency.yml
  tests/examples/torque/sleep_cancel.yml
  tests/settings/jlse.yml
  tests/settings/nersc.yml
  tests/settings/pbs.yml
Labels: size/L

#1760 Fix wrong lines highlighted in code example for programming environment
  docs/configuring_buildtest/compilers.rst
Labels: size/XS

#1751 Extract linenum from file_regex for metrics
  buildtest/builders/base.py
  buildtest/schemas/definitions.schema.json
  tests/builders/metrics_file_regex_with_invalid_linenum.yml
  tests/builders/metrics_file_regex_with_linenum.yml
  tests/builders/test_builders.py
  tutorials/metrics/metrics_file_regex_with_invalid_linenum.yml
  tutorials/metrics/metrics_file_regex_with_linenum.yml
Labels: size/L
