Repository buildtesters/buildtest, pull requests merged in 2024-05, with the labels that each got.

#1772 Acquire system details and topology information using archspec, psutil and using filesystem and sysctl command
  buildtest/cli/info.py
  buildtest/system.py
  buildtest/tools/cpu.py
  pyproject.toml
Labels: size/L

#1773 Remove Cobalt Scheduler
  .gitlab/jlse.yml
  buildtest/builders/base.py
  buildtest/config.py
  buildtest/executors/cobalt.py
  buildtest/executors/setup.py
  buildtest/scheduler/cobalt.py
  buildtest/scheduler/detection.py
  buildtest/schemas/examples/script.schema.json/valid/job_submission.yml
  buildtest/schemas/examples/settings.schema.json/invalid/invalid_executor_names.yml
  buildtest/schemas/examples/settings.schema.json/valid/cobalt-example.yml
  buildtest/schemas/examples/settings.schema.json/valid/combined_executor.yml
  buildtest/schemas/script.schema.json
  buildtest/schemas/settings.schema.json
  buildtest/schemas/spack.schema.json
  buildtest/settings/config.yml
  docs/batch_support.rst
  docs/buildspecs/spack.rst
  docs/configuring_buildtest/overview.rst
  docs/configuring_buildtest/site_examples.rst
  docs/contributing/regression_testing.rst
  docs/writing_buildspecs/multi_executor.rst
  general_tests/sched/cobalt/commands.yml
  tests/buildsystem/valid_builds/sched_directives.yml
  tests/examples/jlse/hold_job.yml
  tests/examples/jlse/hostname.yml
  tests/settings/jlse.yml
  tests/test_jlse.py
Labels: size/XL

#1774 remove processor property from buildtest configuration
  buildtest/schemas/examples/settings.schema.json/valid/local-executor.yml
  buildtest/schemas/settings.schema.json
  tests/cli/configuration/invalid_executors.yml
Labels: size/S

#1775 add support for specifying paths to search for container 'docker', 'singularity' and 'podman' in configuration file
  buildtest/builders/script.py
  buildtest/schemas/settings.schema.json
  buildtest/settings/config.yml
  docs/configuring_buildtest/overview.rst
Labels: size/L

#1777 Improvements to Builder Class and improvement to container support and enable strict mode for tests
  bash_completion.sh
  buildtest/builders/base.py
  buildtest/builders/script.py
  buildtest/builders/spack.py
  buildtest/buildsystem/builders.py
  buildtest/cli/__init__.py
  buildtest/cli/build.py
  buildtest/main.py
  buildtest/schemas/definitions.schema.json
  buildtest/schemas/settings.schema.json
  buildtest/utils/file.py
  buildtest/utils/tools.py
  docs/gettingstarted/buildingtest.rst
  tests/cli/test_build.py
  tests/utils/test_file.py
  tutorials/strict_example.yml
Labels: size/XL

#1778 Add support for post_run
  buildtest/builders/base.py
  buildtest/schemas/examples/script.schema.json/valid/post_run.yml
  buildtest/schemas/script.schema.json
  buildtest/schemas/spack.schema.json
  docs/writing_buildspecs/comparison_operators.rst
  docs/writing_buildspecs/customize_shell.rst
  docs/writing_buildspecs/multi_executor.rst
  docs/writing_buildspecs/status_check.rst
  tests/builders/post_run.yml
  tests/builders/test_builders.py
  tutorials/post_run.yml
Labels: size/L

#1779 Show content of generated test, build script and output and error in 'buildtest build'
  buildtest/builders/base.py
  buildtest/cli/inspect.py
  buildtest/utils/tools.py
Labels: size/L

#1781 Add documentation for extract line numbers in metrics
  docs/writing_buildspecs/metrics.rst
  tutorials/metrics/metrics_regex_with_linenum.yml
Labels: size/M

#1780 Add utility modules for printing and creating rich tables
  buildtest/builders/base.py
  buildtest/cli/buildspec.py
  buildtest/cli/history.py
  buildtest/cli/inspect.py
  buildtest/cli/report.py
  buildtest/utils/print.py
  buildtest/utils/table.py
  buildtest/utils/tools.py
Labels: size/XL
